// ============ SPRITES: NEW BEASTS ============
// Hi-res (px 1) additions to the older rosters: the Greenwood's bats, boar
// riders and warchiefs, and the Iron Kingdom's gryphon knights. Same grammar
// as sprites.js.

import { INK } from "../data/constants.js";

export const BEAST_SPRITES = {
  // ---- FELL BAT (22x14): two frames of flap, ears like knives, and the
  // same red eyes as everything else the deep wood sends.
  bat: {
    pal: { o: INK, w: "#4a3e50", d: "#372e3e", b: "#6a5a74", e: "#e05248", t: "#c8bca8" },
    px: 1,
    rate: 12,
    frames: [
      [
        "......................",
        "..oo..............oo..",
        ".owwoo..........oowwo.",
        ".owwwwoo..oo..oowwwwo.",
        "..owwwwwooddooowwwwwo.",
        "..odwwwwwddddwwwwwdo..",
        "...odwwwdbddbdwwwdo...",
        "....oodwdbbbbdwdoo....",
        "......oddeddedddo.....",
        ".......odddddddo......",
        "........odtdtdo.......",
        ".........oddddo.......",
        "..........oo.oo.......",
        "......................",
      ],
      [
        "......................",
        "......................",
        "......................",
        "..........oo..........",
        "....ooo..odddo..ooo...",
        "..oowwwooddddddowwwoo.",
        ".owwwwwwddbddbdwwwwwo.",
        "..oddwwwdbbbbbdwwwddo.",
        "....oodddeddedddddoo..",
        ".......odddddddo......",
        "........odtdtdo.......",
        ".........oddddo.......",
        "..........oo.oo.......",
        "......................",
      ],
    ],
  },

  // ---- BOAR RIDER (30x28): a war boar with tusks out and a goblin lancer
  // sitting HIGH on its back where you can see him — spear forward, ears up,
  // both of them entirely committed.
  boarrider: {
    pal: { o: INK, h: "#6a4a34", d: "#523826", m: "#3c2a1c", t: "#e0d6ba", g: "#6aa04f", l: "#86ba64", e: "#c8453a", s: "#8a6238", b: "#5a5464", k: "#e05248" },
    px: 1,
    rate: 9,
    frames: [
      [
        "..........ooo.........oo......",
        ".........olggo.......oso......",
        ".........oggeo......oso.......",
        ".........ogggo.....oso........",
        "..........oggoo...oso.........",
        ".........obbbbbo.oso..........",
        "........obbbbbbooso...........",
        "........obbbbbosso............",
        ".........oggoggo..............",
        "......ooooggoggoo.............",
        ".....ohhhhoggoggho............",
        "....ohhhhhhooohhhhoooo........",
        "...ohmhhhhhhhhhhhhhhhhoo......",
        "..ohmhhhhhhhhhhhhhhhhhhho.....",
        "..ohmhhhhhhhhhhhhhhhhhdhho....",
        ".ohhmhhhhhhhhhhhhhhhhdddhho...",
        ".ohhhhhhhhhhhhhhhhhhhdodeo....",
        ".ohhhhhhhhhhhhhhhhhhddoddo....",
        ".odhhhhhhhhhhhhhhhdddo.oto....",
        ".odhhhdhhhhhhhhhhddddo.otto...",
        "..odhhdhhhhhhhhoddhddo..oo....",
        "..odhhodhhhhhho..odhho........",
        "...odho.odddho....odho........",
        "...odho..odho.....oddho.......",
        "..oddho..oddho....odddo.......",
        "..odddo...oddo.....ooo........",
        "...ooo.....oo.................",
        "..............................",
      ],
      [
        "..........ooo.........oo......",
        ".........olggo.......oso......",
        ".........oggeo......oso.......",
        ".........ogggo.....oso........",
        "..........oggoo...oso.........",
        ".........obbbbbo.oso..........",
        "........obbbbbbooso...........",
        "........obbbbbosso............",
        ".........oggoggo..............",
        "......ooooggoggoo.............",
        ".....ohhhhoggoggho............",
        "....ohhhhhhooohhhhoooo........",
        "...ohmhhhhhhhhhhhhhhhhoo......",
        "..ohmhhhhhhhhhhhhhhhhhhho.....",
        "..ohmhhhhhhhhhhhhhhhhhdhho....",
        ".ohhmhhhhhhhhhhhhhhhhdddhho...",
        ".ohhhhhhhhhhhhhhhhhhhdodeo....",
        ".ohhhhhhhhhhhhhhhhhhddoddo....",
        ".odhhhhhhhhhhhhhhhdddo.oto....",
        ".odhhhdhhhhhhhhhhddddo.otto...",
        "..odhhdhhhhhhhhoddhddo..oo....",
        "..odhoddhhhhhho.odhho.........",
        "..odho..odddho...oddo.........",
        ".odho.....odho....oddo........",
        ".odho....oddho.....oddo.......",
        ".oddo....oddo.......oddo......",
        "..oo......oo.........oo.......",
        "..............................",
      ],
    ],
  },

  // ---- HOBGOBLIN WARCHIEF (26x30): a head taller than any goblin, in
  // scavenged plate, with the totem-banner lashed to his back — the red
  // pennant is what the rest of the party is following.
  hobgoblin: {
    pal: { o: INK, g: "#5c8a44", l: "#78a858", d: "#446630", e: "#e05248", t: "#ece0c4", m: "#6a6a72", s: "#5f4326", r: "#b0483c", b: "#6e4c28" },
    px: 1,
    rate: 5,
    frames: [
      [
        "...................oso....",
        "..................orrso...",
        "..................orrrso..",
        "..................orrso...",
        ".......oooooooo...oso.....",
        "......oollllggoo..oso.....",
        ".....olllggggggdo.oso.....",
        "....ollgggggggggdooso.....",
        "....olggggggggggdooso.....",
        "....ogoeeggggeeogooso.....",
        "....oggeeggggeegggoso.....",
        "....olgggdggdgggdoso......",
        ".....oggdt.tdggdo.oso.....",
        ".....ogggddddggdoooso.....",
        "......odggggggdo.osso.....",
        "....oommmmmmmmmoosso......",
        "...ommmlmmmmmmmmsso.......",
        "..ommolmmmmmmmomms........",
        "..ommogmmmmmmmogmmo.......",
        "..ogdogmmmmmmmogddo.......",
        "..ogdogmmmmmmmogddo.......",
        "..ogdoommmmmmmoogdo.......",
        "...oo.ommmmmmmo..oo.......",
        "......obbbbbbbo...........",
        ".....obbgggggbbo..........",
        ".....ogggo.ogggo..........",
        ".....oggdo.oggdo..........",
        ".....oggdo.oggdo..........",
        "....odggdo.odggdo.........",
        "....oddoo...oddoo.........",
      ],
      [
        "...................oso....",
        "..................osrro...",
        ".................osrrro...",
        "..................osrro...",
        ".......oooooooo...oso.....",
        "......oollllggoo..oso.....",
        ".....olllggggggdo.oso.....",
        "....ollgggggggggdooso.....",
        "....olggggggggggdooso.....",
        "....ogoeeggggeeogooso.....",
        "....oggeeggggeegggoso.....",
        "....olgggdggdgggdoso......",
        ".....oggdt.tdggdo.oso.....",
        ".....ogggddddggdoooso.....",
        "......odggggggdo.osso.....",
        "....oommmmmmmmmoosso......",
        "...ommmlmmmmmmmmsso.......",
        "..ommolmmmmmmmomms........",
        "..ommogmmmmmmmogmmo.......",
        "..ogdogmmmmmmmogddo.......",
        "..ogdogmmmmmmmogddo.......",
        "..ogdoommmmmmmoogdo.......",
        "...oo.ommmmmmmo..oo.......",
        "......obbbbbbbo...........",
        ".....obbgggggbbo..........",
        "......ogggogggo...........",
        "......oggdoggdo...........",
        ".....oggdo..oggdo.........",
        ".....odgdo..odgdo.........",
        ".....oddo....oddo.........",
      ],
    ],
    fight: [
      [
        "...................oso....",
        "..................orrso...",
        "..................orrrso..",
        "..................orrso...",
        ".......oooooooo...oso.....",
        "......oollllggoo..oso.....",
        ".....olllggggggdo.oso.....",
        "....ollgggggggggdooso.....",
        "....olggggggggggdooso.....",
        "....ogoeeggggeeogooso.....",
        "....oggeeggggeegggoso.....",
        "....olgggdggdgggdoso......",
        ".....oggoooooogdo.oso.....",
        ".....ogotttttogdoooso.....",
        "......odggggggdo.osso.....",
        "....oommmmmmmmmoosso.oo...",
        "...ommmlmmmmmmmmssoomto...",
        "..ommolmmmmmmmommsomto....",
        "..ommogmmmmmmmogmmmto.....",
        "..ogdogmmmmmmmogdmto......",
        "..ogdogmmmmmmmogddo.......",
        "..ogdoommmmmmmoogdo.......",
        "...oo.ommmmmmmo..oo.......",
        "......obbbbbbbo...........",
        ".....obbgggggbbo..........",
        ".....ogggo.ogggo..........",
        ".....oggdo.oggdo..........",
        ".....oggdo.oggdo..........",
        "....odggdo.odggdo.........",
        "....oddoo...oddoo.........",
      ],
      [
        "...................oso....",
        "..................orrso...",
        "..................orrrso..",
        "..................orrso...",
        ".......oooooooo...oso.....",
        "......oollllggoo..oso.....",
        ".....olllggggggdo.oso.....",
        "....ollgggggggggdooso.....",
        "....olggggggggggdooso.....",
        "....ogoeeggggeeogooso.....",
        "....oggeeggggeegggoso.....",
        "....olgggdggdgggdoso......",
        ".....oggoooooogdo.oso.....",
        ".....ogotttttogdoooso.....",
        "......odggggggdo.osso.....",
        "....oommmmmmmmmoosso......",
        "...ommmlmmmmmmmmssooooo...",
        "..ommolmmmmmmmommsomtto...",
        "..ommogmmmmmmmogmmooomto..",
        "..ogdogmmmmmmmogddo..oo...",
        "..ogdogmmmmmmmogddo.......",
        "..ogdoommmmmmmoogdo.......",
        "...oo.ommmmmmmo..oo.......",
        "......obbbbbbbo...........",
        ".....obbgggggbbo..........",
        ".....ogggo.ogggo..........",
        ".....oggdo.oggdo..........",
        ".....oggdo.oggdo..........",
        "....odggdo.odggdo.........",
        "....oddoo...oddoo.........",
      ],
    ],
  },

  // ---- GRYPHON KNIGHT (32x28): eagle head high at the right with a gold
  // hooked beak, one great wing over the back, lion hindquarters, and an
  // armored rider tucked behind the neck with a couched lance.
  gryphon: {
    pal: { o: INK, f: "#e8e2d4", d: "#c0b8a6", w: "#948c7c", a: "#8a8f9a", m: "#5f636d", k: "#e0b855", l: "#b08a54", n: "#8a6a3c", e: "#2b2a33", p: "#6c7c94" },
    px: 1,
    rate: 8,
    frames: [
      [
        "................................",
        "..........oooo..................",
        "........oowwwwoo................",
        "......oowwwwwwwwoo..............",
        ".....owwwwwwwwwwwwoo............",
        "....owwwwwwwwwwwwwwwoo..........",
        "....odwwwwwwwwwwwwwwwwo.........",
        ".....oddwwwwwwwwwwwwwo..........",
        ".......oddddwwwwwwoo..ooo.......",
        "..........ooooooo...offffo......",
        "..............oaao.offoefo......",
        ".............oaaaaoofffffokkko..",
        ".............oamaaofffffkkkoo...",
        ".....ooooooopaaaaafffffokko.....",
        "....ollllooffaaaoffffffoo.......",
        "...olllllllffffffffffffo........",
        "..ollllllllffffffffffffo........",
        "..olllllllllffffffffffdo........",
        "..onllllllllffffffffffdo........",
        "..onllllllllofffffffddo.........",
        "..oonllllllooffffffddo..........",
        "...oollllo..offffoddo...........",
        "....olllo....offo.odo...........",
        "....ollo.....offo..odo..........",
        "...ollo......odffo..odo.........",
        "...onno......okkko..okko........",
        "...oo.........ooo....oo.........",
        "................................",
      ],
      [
        "................................",
        "................................",
        "................................",
        "................................",
        "......oo........................",
        "......odoo......................",
        "......oddddoo...................",
        ".......odddddwwoo...............",
        ".......oodwwwwwwwoo...ooo.......",
        ".........oowwwwwwwo.offffo......",
        "..............oaawwoffoefo......",
        ".............oaaaaoofffffokkko..",
        ".............oamaaofffffkkkoo...",
        ".....ooooooopaaaaafffffokko.....",
        "....ollllooffaaaoffffffoo.......",
        "...olllllllffffffffffffo........",
        "..ollllllllffffffffffffo........",
        "..olllllllllffffffffffdo........",
        "..onllllllllffffffffffdo........",
        "..onllllllllofffffffddo.........",
        "..oonllllllooffffffddo..........",
        "...oollllo..offffoddo...........",
        "....olllo....offo..odo..........",
        "....ollo.....offo...odo.........",
        "...ollo.....odffo...odo.........",
        "...onno.....okkko...okko........",
        "...oo........ooo.....oo.........",
        "................................",
      ],
    ],
  },
};
