// ============ PIXEL SPRITES ============
// Hand-made 2-frame sprite maps for every character, their color palettes,
// the little "mini" figures that stand on towers, and the drawSprite routine
// that paints a sprite map onto a canvas one pixel-cell at a time.

import { INK, CELL } from "../data/constants.js";

export const SPRITES = {
  // v2 high-fidelity goblin: round head with close-set eyes, long arms hanging
  // to the ground (they pump while he scampers), loincloth, 4-frame walk and a
  // 2-frame arms-overhead jaws-wide fight flail. Highlight (l), teeth (t), cloth (b).
  // Hi-res goblin (26x26 @ px 1): domed head, heavy brow, close-set red
  // eyes, gapped grin, long arms that swing as he scampers, loincloth.
  goblin: {
    pal: { o: INK, g: "#6aa04f", l: "#86ba64", d: "#4d7639", e: "#c8453a", t: "#ece0c4", b: "#6e4c28" },
    px: 1,
    rate: 10,
    frames: [
      [
        ".........oooooooo.........",
        ".......oollllllggoo.......",
        "......olllggggggggdo......",
        ".....olllggggggggggdo.....",
        ".....ollggggggggggggdo....",
        "....ollgggggggggggggdo....",
        "....ogddddddddddddddo.....",
        "....ogoeeeggeeeogggo......",
        "....oggeeeggeeegggdo......",
        "....olggggdggdggggdo......",
        ".....oggggdggdggggdo......",
        ".....ogottottottogdo......",
        ".....oggddddddddgdo.......",
        "......oddggggggddo........",
        "...ollgggggggggggggggddo..",
        "...olggdolggggggdolggdo...",
        "...olggdolggggggdolggdo...",
        "...olggdolggggggdolggdo...",
        "...olggdoddddddddolggdo...",
        "...olggdobbbbbbbbolggdo...",
        "...ollgdobbbbbbbbolgddo...",
        ".......olggo..oggdo.......",
        ".......olggo..oggdo.......",
        ".......olggo..oggdo.......",
        ".......olggo..oggdo.......",
        "......odddddo..odddddo....",
      ],
      [
        ".........oooooooo.........",
        ".......oollllllggoo.......",
        "......olllggggggggdo......",
        ".....olllggggggggggdo.....",
        ".....ollggggggggggggdo....",
        "....ollgggggggggggggdo....",
        "....ogddddddddddddddo.....",
        "....ogoeeeggeeeogggo......",
        "....oggeeeggeeegggdo......",
        "....olggggdggdggggdo......",
        ".....oggggdggdggggdo......",
        ".....ogottottottogdo......",
        ".....oggddddddddgdo.......",
        "......oddggggggddo........",
        "...ollgggggggggggggggddo..",
        "...olggdolggggggdolggdo...",
        "...olggdolggggggdolggdo...",
        "...olggdolggggggdolggdo...",
        "...olggdoddddddddolggdo...",
        "...ollgdobbbbbbbbolgddo...",
        "........obbbbbbbbo........",
        "..............oggdo.......",
        ".......olggo..oggdo.......",
        ".......olggo..oggdo.......",
        ".......olggo..oggdo.......",
        "......odddddo..odddddo....",
      ],
      [
        ".........oooooooo.........",
        ".......oollllllggoo.......",
        "......olllggggggggdo......",
        ".....olllggggggggggdo.....",
        ".....ollggggggggggggdo....",
        "....ollgggggggggggggdo....",
        "....ogddddddddddddddo.....",
        "....ogoeeeggeeeogggo......",
        "....oggeeeggeeegggdo......",
        "....olggggdggdggggdo......",
        ".....oggggdggdggggdo......",
        ".....ogottottottogdo......",
        ".....oggddddddddgdo.......",
        "......oddggggggddo........",
        "...ollgggggggggggggggddo..",
        "...olggdolggggggdolggdo...",
        "...olggdolggggggdolggdo...",
        "...olggdolggggggdolggdo...",
        "...olggdoddddddddolggdo...",
        "...olggdobbbbbbbbolggdo...",
        "...ollgdobbbbbbbbolgddo...",
        ".......olggo..oggdo.......",
        ".......olggo..oggdo.......",
        ".......olggo..oggdo.......",
        ".......olggo..oggdo.......",
        "......odddddo..odddddo....",
      ],
      [
        ".........oooooooo.........",
        ".......oollllllggoo.......",
        "......olllggggggggdo......",
        ".....olllggggggggggdo.....",
        ".....ollggggggggggggdo....",
        "....ollgggggggggggggdo....",
        "....ogddddddddddddddo.....",
        "....ogoeeeggeeeogggo......",
        "....oggeeeggeeegggdo......",
        "....olggggdggdggggdo......",
        ".....oggggdggdggggdo......",
        ".....ogottottottogdo......",
        ".....oggddddddddgdo.......",
        "......oddggggggddo........",
        "...ollgggggggggggggggddo..",
        "...olggdolggggggdolggdo...",
        "...olggdolggggggdolggdo...",
        "...olggdolggggggdolggdo...",
        "...olggdoddddddddolggdo...",
        "...ollgdobbbbbbbbolgddo...",
        "........obbbbbbbbo........",
        ".......olggo..............",
        ".......olggo..oggdo.......",
        ".......olggo..oggdo.......",
        ".......olggo..oggdo.......",
        "......odddddo..odddddo....",
      ],
    ],
    fight: [
      [
        ".........oooooooo.........",
        ".......oollllllggoo.......",
        "......olllggggggggdo......",
        ".....olllggggggggggdo.....",
        ".....ollggggggggggggdo....",
        "....ollgggggggggggggdo....",
        "....ogddddddddddddddo.....",
        "....ogoeeeggeeeogggo......",
        "....oggeeeggeeegggdo......",
        "....olggggdggdggggdo......",
        ".....oggoooooooogdo.......",
        ".....ogottttttttogdo......",
        ".....ogoeooooooeogdo......",
        "......odottttttodo........",
        "...ollgggggggggggggggddo..",
        "...olggdolggggggdolggdo...",
        "...olggdolggggggdolggdo...",
        "...ollgdolggggggdolgddo...",
        "........oddddddddo........",
        "........obbbbbbbbo........",
        "........obbbbbbbbo........",
        ".......olggo..oggdo.......",
        ".......olggo..oggdo.......",
        ".......olggo..oggdo.......",
        ".......olggo..oggdo.......",
        "......odddddo..odddddo....",
      ],
      [
        ".........oooooooo.........",
        ".......oollllllggoo.......",
        "......olllggggggggdo......",
        ".....olllggggggggggdo.....",
        ".....ollggggggggggggdo....",
        "....ollgggggggggggggdo....",
        "....ogddddddddddddddo.....",
        "....ogoeeeggeeeogggo......",
        "....oggeeeggeeegggdo......",
        "....olggggdggdggggdo......",
        ".....oggoooooooogdo.......",
        ".....ogottttttttogdo......",
        ".....ogoeooooooeogdo......",
        "......odottttttodo........",
        "...ollgggggggggggggggddo..",
        "...olggdolggggggdolggdo...",
        "...olggdolggggggdolggdo...",
        "...olggdolggggggdolggdo...",
        "...olggdoddddddddolggdo...",
        "...olggdobbbbbbbbolggdo...",
        "...ollgdobbbbbbbbolgddo...",
        "..............oggdo.......",
        ".......olggo..oggdo.......",
        ".......olggo..oggdo.......",
        ".......olggo..oggdo.......",
        "......odddddo..odddddo....",
      ],
    ],
  },
  // v2 dire wolf: 4-frame gallop (reach / gather / bunch / kick) with a pale
  // belly and streaming tail; fight cycle is a hackles-up crouch with bared fangs.
  wolf: {
    pal: { o: INK, w: "#8f929c", d: "#63666f", l: "#aab0ba", e: "#d8b34a", n: "#2b2a33", t: "#ece0c4" },
    rate: 12,
    frames: [
      [
        "............oo..",
        ".o.........oddo.",
        "odo.ooooooowwddo",
        ".odowwwwwwwwweoo",
        "..owwwwwwwwwwonn",
        "..odwwllllwwdo..",
        "...owllllllwo...",
        "..od......odo...",
        ".od........odo..",
        "od..........od..",
      ],
      [
        "o...........oo..",
        ".do.........oddo",
        ".odooooooo.wwddo",
        ".odowwwwwwwwweoo",
        "..owwwwwwwwwwonn",
        "..odwwllllwwdo..",
        "...owllllllwo...",
        "...od....odo....",
        "....od...od.....",
        "................",
      ],
      [
        "............oo..",
        ".o.........oddo.",
        "odo.ooooooowwddo",
        ".odowwwwwwwwweoo",
        "..owwwwwwwwwwonn",
        "..odwwllllwwdo..",
        "...owllllllwo...",
        ".....odo.od.....",
        "....do..od......",
        "...do......od...",
      ],
      [
        "o...........oo..",
        ".do.........oddo",
        ".odooooooo.wwddo",
        ".odowwwwwwwwweoo",
        "..owwwwwwwwwwonn",
        "..odwwllllwwdo..",
        "...owllllllwo...",
        "...odo....od....",
        "..od........od..",
        "................",
      ],
    ],
    fight: [
      [
        "............oo..",
        ".o.........oddo.",
        "ododooooooowwddo",
        ".odowwwwwwwwweoo",
        "..owwwwwwwwwwoo.",
        "..odwwllllwwddto",
        "...owllllllwo...",
        "..odo...odo.odo.",
        "..oo.....oo..oo.",
        "................",
      ],
      [
        "o...........oo..",
        ".do........oddo.",
        "ododooooooowwddo",
        ".odowwwwwwwwweoo",
        "..owwwwwwwwwwonn",
        "..odwwllllwwdo..",
        "...owllllllwo...",
        "..odo...odo.odo.",
        "..oo.....oo..oo.",
        "................",
      ],
    ],
  },
  // v2 orc: mohawked bruiser hauling a wooden club over one shoulder; 4-frame
  // march, and a fight cycle that raises the club overhead and slams it down.
  orc: {
    pal: { o: INK, g: "#7d9a4a", l: "#95b45e", d: "#5c7638", t: "#ece0c4", e: "#c8453a", c: "#6e4f2c", m: "#63666f", b: "#6e4c28", s: "#e0b088" },
    rate: 7,
    frames: [
      [
        "..occo........",
        "..occo....obbo",
        "...oc.oooo.obo",
        "..oooggggo.bo.",
        ".omolggego.bo.",
        ".omoggggtobo..",
        "..oggggto.bo..",
        "..ogddddgobo..",
        "..ogddddgso...",
        "...ogddgo.....",
        "...od..do.....",
        "...od..do.....",
        "...oo..oo.....",
      ],
      [
        "..occo........",
        "..occo....obbo",
        "...oc.oooo.obo",
        "..oooggggo.bo.",
        ".omolggego.bo.",
        ".omoggggtobo..",
        "..oggggto.bo..",
        "..ogddddgobo..",
        "..ogddddgso...",
        "...ogddgo.....",
        "....od.do.....",
        "....od.do.....",
        "....oo.oo.....",
      ],
      [
        "..occo........",
        "..occo....obbo",
        "...oc.oooo.obo",
        "..oooggggo.bo.",
        ".omolggego.bo.",
        ".omoggggtobo..",
        "..oggggto.bo..",
        "..ogddddgobo..",
        "..ogddddgso...",
        "...ogddgo.....",
        "..od....do....",
        ".od......do...",
        ".oo......oo...",
      ],
      [
        "..occo........",
        "..occo....obbo",
        "...oc.oooo.obo",
        "..oooggggo.bo.",
        ".omolggego.bo.",
        ".omoggggtobo..",
        "..oggggto.bo..",
        "..ogddddgobo..",
        "..ogddddgso...",
        "...ogddgo.....",
        "...od...do....",
        "...od...do....",
        "...oo...oo....",
      ],
    ],
    fight: [
      [
        "..........obbo",
        "..occo....obbo",
        "...oc.oooo.bo.",
        "..oooggggo.bo.",
        ".omolggegosbo.",
        ".omoggggto.o..",
        "..oggggto.....",
        "..ogddddgo....",
        "..ogddddgo....",
        "...ogddgo.....",
        "..od....do....",
        "..od....do....",
        "..oo....oo....",
      ],
      [
        "..occo........",
        "..occo........",
        "...oc.oooo....",
        "..oooggggo....",
        ".omolggego....",
        ".omoggggto....",
        "..oggggtobbo..",
        "..ogddddgobbo.",
        "..ogddddgso...",
        "...ogddgo.....",
        "..od....do....",
        "..od....do....",
        "..oo....oo....",
      ],
    ],
  },
  // v2 ironclad: walking bunker — plume flutters, visor slit glints, tower
  // shield always planted on the right; fight cycle is a grinding shield shove.
  armored: {
    pal: { o: INK, s: "#9aa0ac", d: "#63676f", h: "#c4c8d0", l: "#dde2ea", r: "#b04a3c", g: "#d8b34a" },
    rate: 5,
    frames: [
      [
        ".....orro....",
        ".....orro....",
        "....olhhho...",
        "....oo..oo...",
        "....ohhhhoho.",
        "...ossssohho.",
        "...osddsohgo.",
        "...ossssohho.",
        "...osddsohho.",
        "....ossoohho.",
        "....od.do.o..",
        "....od.do....",
        "....oo.oo....",
      ],
      [
        ".....orro....",
        ".....orro....",
        "....olhhho...",
        "....oo..oo...",
        "....ohhhhoho.",
        "...ossssohho.",
        "...osddsohgo.",
        "...ossssohho.",
        "...osddsohho.",
        "....ossoohho.",
        "...od...do.o.",
        "...od...do...",
        "...oo...oo...",
      ],
      [
        "....orro.....",
        "....orro.....",
        "....olhhho...",
        "....oolloo...",
        "....ohhhhoho.",
        "...ossssohho.",
        "...osddsohgo.",
        "...ossssohho.",
        "...osddsohho.",
        "....ossoohho.",
        "....od.do.o..",
        "....od.do....",
        "....oo.oo....",
      ],
      [
        "....orro.....",
        "....orro.....",
        "....olhhho...",
        "....oolloo...",
        "....ohhhhoho.",
        "...ossssohho.",
        "...osddsohgo.",
        "...ossssohho.",
        "...osddsohho.",
        "....ossoohho.",
        "...od...do.o.",
        "...od...do...",
        "...oo...oo...",
      ],
    ],
    fight: [
      [
        ".....orro....",
        ".....orro....",
        "....olhhho...",
        "....oolloo...",
        "....ohhhhoho.",
        "...ossssohho.",
        "...osddsohgo.",
        "...ossssohho.",
        "...osddsohho.",
        "....ossoohho.",
        "...od...do.o.",
        "...od...do...",
        "...oo...oo...",
      ],
      [
        "....orro.....",
        "....orro.....",
        ".....olhhho..",
        ".....oolloo..",
        ".....ohhhhoho",
        "....ossssohho",
        "....osddsohgo",
        "....ossssohho",
        "....osddsohho",
        ".....ossoohho",
        "....od..do.o.",
        "....od..do...",
        "....oo..oo...",
      ],
    ],
  },
  // v2 troll: ponderous 4-phase lumber with a swaying spiked club; fight
  // cycle heaves the club overhead in both hands and brings it down.
  troll: {
    pal: { o: INK, g: "#6f8a55", d: "#54683f", n: "#8fa868", c: "#5f4326", y: "#d8b34a", t: "#ece0c4" },
    rate: 5,
    frames: [
      [
        "....ooooo.......",
        "...ogggggo......",
        "..ogggggggo.....",
        ".ogggggggggoo...",
        ".oggdgggggyno...",
        ".ogddgggggnno...",
        ".ogddgggtggo.c..",
        ".oggddddggo..c..",
        "..ogddddggo..c..",
        "..oggddggo..cc..",
        "...ogggggo..cc..",
        "...od...do..oo..",
        "...od...do......",
        "..ood...doo.....",
        "..oo.....oo.....",
      ],
      [
        "....ooooo.......",
        "...ogggggo......",
        "..ogggggggo.....",
        ".ogggggggggoo...",
        ".oggdgggggyno...",
        ".ogddgggggnno...",
        ".ogddgggtggo.c..",
        ".oggddddggo.c...",
        "..ogddddggo.c...",
        "..oggddggo.cc...",
        "...ogggggo.cc...",
        "...od...do.oo...",
        "...od....do.....",
        "..ood....doo....",
        "..oo......oo....",
      ],
      [
        "....ooooo.......",
        "...ogggggo......",
        "..ogggggggo.....",
        ".ogggggggggoo...",
        ".oggdgggggyno...",
        ".ogddgggggnno...",
        ".ogddgggtggo.c..",
        ".oggddddggo..c..",
        "..ogddddggo..c..",
        "..oggddggo..cc..",
        "...ogggggo..cc..",
        "..od.....do.oo..",
        "..od.....do.....",
        ".ood.....doo....",
        ".oo.......oo....",
      ],
      [
        "....ooooo.......",
        "...ogggggo......",
        "..ogggggggo.....",
        ".ogggggggggoo...",
        ".oggdgggggyno...",
        ".ogddgggggnno...",
        ".ogddgggtggo.c..",
        ".oggddddggo..cc.",
        "..ogddddggo..cc.",
        "..oggddggo...cc.",
        "...ogggggo...oo.",
        "...od...do......",
        "...od...do......",
        "..ood...doo.....",
        "..oo.....oo.....",
      ],
    ],
    fight: [
      [
        "....ooooo...cc..",
        "...ogggggo..cc..",
        "..ogggggggo.cc..",
        ".ogggggggggooc..",
        ".oggdgggggyngo..",
        ".ogddgggggnngo..",
        ".ogddgggtgggo...",
        ".oggddddggo.....",
        "..ogddddggo.....",
        "..oggddggo......",
        "...ogggggo......",
        "..od.....do.....",
        "..od.....do.....",
        ".ood.....doo....",
        ".oo.......oo....",
      ],
      [
        "....ooooo.......",
        "...ogggggo......",
        "..ogggggggo.....",
        ".ogggggggggoo...",
        ".oggdgggggyno...",
        ".ogddgggggnno...",
        ".ogddgggtggocc..",
        ".oggddddggoocc..",
        "..ogddddggo.....",
        "..oggddggo......",
        "...ogggggo......",
        "...od...do......",
        "...od...do......",
        "..ood...doo.....",
        "..oo.....oo.....",
      ],
    ],
  },
  // v2 dragon: full 4-frame wing beat (raised, level, swept-down, level) —
  // the level stroke appears twice so the wings ping-pong smoothly.
  dragon: {
    pal: { o: INK, r: "#b04a3c", d: "#7d3329", y: "#e0c070", h: "#ece0c4", e: "#e8c14a", f: "#d88a3f" },
    rate: 8,
    frames: [
      [
        "......orro..............",
        ".....orrrro.............",
        "....orrrrrro............",
        "...orrrrrrro....oho.oho.",
        "....orrrrro....orrrorro.",
        ".....orro.....orrrrrrro.",
        "oo....orro...orrrrerrro.",
        "oddo...orroorrrrrrrrroo.",
        ".oddoo.orrrrrrrrrrrfo...",
        "..odddorrrrrrrrryyoof...",
        "...oodrrrrrrrryyyyo.....",
        ".....orrrrrryyyyyo......",
        "......orrrrryyyyo.......",
        ".......orrrrrroo........",
        "........oooooo..........",
        "........................",
      ],
      [
        "........................",
        "........................",
        "........................",
        "................oho.oho.",
        "...............orrrorro.",
        "..ooooooooo...orrrrrrro.",
        "oo.orrrrrrrooorrrrerrro.",
        "oddo.oooooooorrrrrrrroo.",
        ".oddoo.orrrrrrrrrrrfo...",
        "..odddorrrrrrrrryyoof...",
        "...oodrrrrrrrryyyyo.....",
        ".....orrrrrryyyyyo......",
        "......orrrrryyyyo.......",
        ".......orrrrrroo........",
        "........oooooo..........",
        "........................",
      ],
      [
        "........................",
        "........................",
        "................oho.oho.",
        "...............orrrorro.",
        "..............orrrrrrro.",
        "oo...........orrrrerrro.",
        "oddo.....ooorrrrrrrrroo.",
        ".oddoo..orrrrrrrrrrrfo..",
        "..odddorrrrrrrrryyoof...",
        "...oodrrrrrrrryyyyo.....",
        "....orrrrrrryyyyyo......",
        "...orrrrrrryyyyo........",
        "..orrrrrorrrroo.........",
        ".orrrro..oooo...........",
        "..ooo...................",
        "........................",
      ],
      [
        "........................",
        "........................",
        "........................",
        "................oho.oho.",
        "...............orrrorro.",
        "..ooooooooo...orrrrrrro.",
        "oo.orrrrrrrooorrrrerrro.",
        "oddo.oooooooorrrrrrrroo.",
        ".oddoo.orrrrrrrrrrrfo...",
        "..odddorrrrrrrrryyoof...",
        "...oodrrrrrrrryyyyo.....",
        ".....orrrrrryyyyyo......",
        "......orrrrryyyyo.......",
        ".......orrrrrroo........",
        "........oooooo..........",
        "........................",
      ],
    ],
  },
  // goblin shaman: bone-masked mystic in a rune-painted robe, planting his
  // skull-topped staff with every stride. Mask (b), robe (c), runes (r).
  shaman: {
    pal: { o: INK, g: "#6aa04f", l: "#86ba64", d: "#4d7639", e: "#c8453a", b: "#ece0c4", c: "#6e4c28", s: "#5f4326", r: "#b08ad8", k: "#e8d47a" },
    rate: 6,
    frames: [
      [
        "...obbbo.....",
        "..obrbbrbo.k.",
        "..obbbbbbo.s.",
        "..obebbebo.s.",
        "...ogggo...s.",
        ".ogoccccogos.",
        "..occccco..s.",
        "..ocrcrco..s.",
        "..occccco..s.",
        "...occco.....",
        "...od.do.....",
        "...oo.oo.....",
      ],
      [
        "...obbbo.....",
        "..obrbbrbo.k.",
        "..obbbbbbo.s.",
        "..obebbebo.s.",
        "...ogggo...s.",
        ".ogoccccogos.",
        "..occccco..s.",
        "..ocrcrco..s.",
        "..occccco..s.",
        "...occco.....",
        "....od.do....",
        "....oo.oo....",
      ],
    ],
  },
  // necromancer: a hooded revenant — skull face, green witch-fire eyes, a
  // staff crowned with a grave-light orb. No feet: the robe drifts.
  necro: {
    pal: { o: INK, p: "#4a3a5e", q: "#6a5688", b: "#ece0c4", e: "#7cc85c", s: "#5f4326", g: "#b08ad8" },
    rate: 4,
    frames: [
      [
        "....ooooo.gg.",
        "...opppppo.gg",
        "..oppbbbppo.s",
        "..opbebebpo.s",
        "..oppbbbppo.s",
        "...opppppo..s",
        "..opppppppo.s",
        ".oppqpppqppos",
        ".opppppppppos",
        ".opqqqqqpo..s",
        "..opppppppo.s",
        "..opppppppo.s",
        "...ooooooo..s",
        "....p..p.....",
      ],
      [
        "....ooooo.gg.",
        "...opppppo.gg",
        "..oppbbbppo.s",
        "..opbebebpo.s",
        "..oppbbbppo.s",
        "...opppppo..s",
        "..opppppppo.s",
        ".oppqpppqppos",
        ".opppppppppos",
        ".opqqqqqpo..s",
        "..opppppppo.s",
        "..opppppppo.s",
        "...ooooooo..s",
        "..p....p.....",
      ],
    ],
  },
  // ---- THE IRON KINGDOM ----
  // A drilled army rather than a horde: shared steel-and-blue livery, upright
  // postures, and silhouettes you can tell apart at a glance — shield, bow,
  // crest, horse, mitre, wheels, banner.
  levy: {
    pal: { o: INK, s: "#b9c0cc", m: "#8b93a2", k: "#5e6675", c: "#3f6ea8", d: "#2d5080", f: "#e0b088", w: "#8a6238" },
    rate: 6,
    frames: [
      [
        "...oooo.......",
        "..osssso....o.",
        "..osffso...o..",
        "..oomsmo..o...",
        ".okocccko.o...",
        ".okoccckofoo..",
        ".okoccckoossso",
        "..oocccoo.osso",
        "...oddddo.osso",
        "...od.ddo.ooo.",
        "...od..do.....",
        "...od..do.....",
        "...oo..oo.....",
      ],
      [
        "...oooo.......",
        "..osssso....o.",
        "..osffso...o..",
        "..oomsmo..o...",
        ".okocccko.o...",
        ".okoccckofoo..",
        ".okoccckoossso",
        "..oocccoo.osso",
        "...oddddo.osso",
        "...od.ddo.ooo.",
        "....od.do.....",
        "....od.do.....",
        "....oo.oo.....",
      ],
    ],
    fight: [
      [
        "...oooo.......",
        "..osssso......",
        "..osffso......",
        "..oomsmo......",
        ".okocccko.oo..",
        ".okoccckoossso",
        ".okoccckofosso",
        "..oocccoowwwwo",
        "...oddddo.....",
        "...od.ddo.....",
        "..od...do.....",
        "..od...do.....",
        "..oo...oo.....",
      ],
      [
        "...oooo.......",
        "..osssso......",
        "..osffso......",
        "..oomsmo......",
        ".okocccko.oo..",
        ".okoccckoossso",
        ".okoccckofosso",
        "..oocccoo.wwwo",
        "...oddddo.....",
        "...od.ddo.....",
        "...od..do.....",
        "...od..do.....",
        "...oo..oo.....",
      ],
    ],
  },
  // kettle-helm brim reads instantly at 15px; the bow sits across the body
  crossbow: {
    pal: { o: INK, s: "#b9c0cc", m: "#8b93a2", k: "#5e6675", c: "#3f6ea8", d: "#2d5080", f: "#e0b088", w: "#8a6238" },
    rate: 6,
    frames: [
      [
        "..oooooo......",
        ".osssssso.....",
        "..osffso......",
        "..oomsmo......",
        ".okocccko.....",
        ".okoccckoowwo.",
        ".okoccckofmmmo",
        "..oocccoo.wwo.",
        "...oddddo.....",
        "...od.ddo.....",
        "...od..do.....",
        "...od..do.....",
        "...oo..oo.....",
      ],
      [
        "..oooooo......",
        ".osssssso.....",
        "..osffso......",
        "..oomsmo......",
        ".okocccko.....",
        ".okoccckoowwo.",
        ".okoccckofmmmo",
        "..oocccoo.wwo.",
        "...oddddo.....",
        "...od.ddo.....",
        "....od.do.....",
        "....od.do.....",
        "....oo.oo.....",
      ],
    ],
    fight: [
      [
        "..oooooo......",
        ".osssssso.....",
        "..osffso..owo.",
        "..oomsmoo.wmw.",
        ".okoccckofmmmo",
        ".okoccckoowmwo",
        ".okoccckoo.w..",
        "..oocccoo.....",
        "...oddddo.....",
        "...od.ddo.....",
        "..od...do.....",
        "..od...do.....",
        "..oo...oo.....",
      ],
      [
        "..oooooo......",
        ".osssssso.....",
        "..osffso......",
        "..oomsmo..owo.",
        ".okocccko.wmw.",
        ".okoccckofmmmo",
        ".okoccckoowmwo",
        "..oocccoo..w..",
        "...oddddo.....",
        "...od.ddo.....",
        "..od...do.....",
        "..od...do.....",
        "..oo...oo.....",
      ],
    ],
  },
  // full plate with a red crest; broader shoulders than the levy, sword up
  sergeant: {
    pal: { o: INK, s: "#b9c0cc", m: "#8b93a2", k: "#5e6675", c: "#3f6ea8", f: "#e0b088", r: "#b5453c", g: "#d8b34a" },
    rate: 5,
    frames: [
      [
        "....rr........",
        "...orro.......",
        "..osssso......",
        "..oskkso......",
        ".oomsssmoo....",
        "osokccckoso.os",
        "osokccckoso.os",
        "osokccckoso.os",
        ".ookccckoo..os",
        "..okkkkko..ogo",
        "..ok...ko.....",
        "..ok...ko.....",
        "..oo...oo.....",
      ],
      [
        "....rr........",
        "...orro.......",
        "..osssso......",
        "..oskkso......",
        ".oomsssmoo....",
        "osokccckoso.os",
        "osokccckoso.os",
        "osokccckoso.os",
        ".ookccckoo..os",
        "..okkkkko..ogo",
        "...ok.ko......",
        "...ok.ko......",
        "...oo.oo......",
      ],
    ],
    fight: [
      [
        "....rr......os",
        "...orro.....os",
        "..osssso....os",
        "..oskkso...ogo",
        ".oomsssmooo...",
        "osokccckoso...",
        "osokccckoso...",
        "osokccckoso...",
        ".ookccckoo....",
        "..okkkkko.....",
        "..ok...ko.....",
        "..ok...ko.....",
        "..oo...oo.....",
      ],
      [
        "....rr........",
        "...orro.......",
        "..osssso......",
        "..oskkso......",
        ".oomsssmoosss.",
        "osokccckooogo.",
        "osokccckoso...",
        "osokccckoso...",
        ".ookccckoo....",
        "..okkkkko.....",
        "..ok...ko.....",
        "..ok...ko.....",
        "..oo...oo.....",
      ],
    ],
  },
  // rider and horse as one wide sprite; the lance runs out over the horse's head
  cavalier: {
    pal: { o: INK, s: "#b9c0cc", m: "#8b93a2", k: "#5e6675", c: "#3f6ea8", f: "#e0b088", r: "#b5453c", h: "#7a5a3c", l: "#96714c", d: "#5f4326", w: "#8a6238" },
    rate: 9,
    frames: [
      [
        ".......oorro.....",
        "......ossssso....",
        "......osffso.....",
        ".....oocccoo.....",
        "....okoccckoo....",
        "....okoccckowwwww",
        "..oohhhhhhhoo.oho",
        ".ohhhhhhhhhhhohho",
        "ohlllhhhhhhhhhhho",
        ".ohhoohhhoohhoohh",
        ".ohho.ohho.ohho..",
        ".od.o.od.o.od.o..",
        ".od...od...od....",
        ".oo...oo...oo....",
      ],
      [
        ".......oorro.....",
        "......ossssso....",
        "......osffso.....",
        ".....oocccoo.....",
        "....okoccckoo....",
        "....okoccckowwwww",
        "..oohhhhhhhoo.oho",
        ".ohhhhhhhhhhhohho",
        "ohlllhhhhhhhhhhho",
        ".ohhoohhhoohhoohh",
        "ohho...ohho..ohho",
        "od.o...od.o..od.o",
        "od......od....od.",
        "oo......oo....oo.",
      ],
      [
        ".......oorro.....",
        "......ossssso....",
        "......osffso.....",
        ".....oocccoo.....",
        "....okoccckoo....",
        "....okoccckowwwww",
        "..oohhhhhhhoo.oho",
        ".ohhhhhhhhhhhohho",
        "ohlllhhhhhhhhhhho",
        ".ohhoohhhoohhoohh",
        "..ohhoohho.ohho..",
        "...od.od.o..od.o.",
        "...od..od....od..",
        "...oo..oo....oo..",
      ],
    ],
  },
  // tall mitre and a long robe; the censer swings on its chain as he walks
  chaplain: {
    pal: { o: INK, s: "#e8e0c8", m: "#c8bfa2", c: "#3f6ea8", d: "#2d5080", f: "#e0b088", g: "#d8b34a", k: "#5e6675" },
    rate: 5,
    frames: [
      [
        "....ogo.......",
        "...osso.......",
        "...osso.......",
        "..osssso......",
        "..osffso......",
        "..oomsmo......",
        ".ogoccccogo...",
        ".ogocccco.o...",
        ".oocddddoo.o..",
        "..oddddddo.o..",
        "..oddddddo.ogo",
        "..odddddddo...",
        "...oooooo.....",
      ],
      [
        "....ogo.......",
        "...osso.......",
        "...osso.......",
        "..osssso......",
        "..osffso......",
        "..oomsmo......",
        ".ogoccccogo...",
        ".ogocccco.oo..",
        ".oocddddoo..o.",
        "..oddddddo..o.",
        "..oddddddo.ogo",
        "..odddddddo...",
        "...oooooo.....",
      ],
    ],
    fight: [
      [
        "....ogo.......",
        "...osso...ogo.",
        "...osso...ogo.",
        "..osssso..ogo.",
        "..osffso...o..",
        "..oomsmoo.....",
        ".ogoccccogo...",
        ".ogocccco.....",
        ".oocddddoo....",
        "..oddddddo....",
        "..oddddddo....",
        "..odddddddo...",
        "...oooooo.....",
      ],
      [
        "....ogo.......",
        "...osso.......",
        "...osso...ogo.",
        "..osssso..ogo.",
        "..osffso..ogo.",
        "..oomsmoo..o..",
        ".ogoccccogo...",
        ".ogocccco.....",
        ".oocddddoo....",
        "..oddddddo....",
        "..oddddddo....",
        "..odddddddo...",
        "...oooooo.....",
      ],
    ],
  },
  // no legs at all: an iron-headed log slung under a roof, rolling on wheels
  ram: {
    pal: { o: INK, w: "#8a6238", d: "#5f4326", m: "#8b93a2", s: "#b9c0cc", k: "#5e6675", c: "#3f6ea8", g: "#d8b34a" },
    rate: 5,
    frames: [
      [
        "...oooooooooo....",
        "..occcccccccco...",
        ".occcccccccccco..",
        "oooooooooooooooo.",
        ".ow..ow..ow..ow..",
        ".ow..ow..ow..ow..",
        ".ooooooooooooooo.",
        ".odwwwwwwwwwwmmso",
        ".odwwwwwwwwwwmmso",
        ".ooooooooooooosoo",
        "..o.oo.oo.oo.o...",
        ".okko.okko.okko..",
        "..oo...oo...oo...",
      ],
      [
        "...oooooooooo....",
        "..occcccccccco...",
        ".occcccccccccco..",
        "oooooooooooooooo.",
        ".ow..ow..ow..ow..",
        ".ow..ow..ow..ow..",
        ".ooooooooooooooo.",
        ".odwwwwwwwwwwmmso",
        ".odwwwwwwwwwwmmso",
        ".ooooooooooooosoo",
        "..o.oo.oo.oo.o...",
        ".okoo.okoo.okoo..",
        "..oo...oo...oo...",
      ],
    ],
  },
  // the tallest silhouette in the game: crested helm, cape, and a banner that
  // stands a head above him
  marshal: {
    pal: { o: INK, s: "#d8dde6", m: "#9aa3b2", k: "#5e6675", c: "#3f6ea8", d: "#2d5080", f: "#e0b088", g: "#d8b34a", r: "#b5453c" },
    rate: 5,
    frames: [
      [
        ".....gg....ooo...",
        "....oggo..orrro..",
        "....ogo..orrrrro.",
        "...ossso.orrgrro.",
        "...oskso.orrrrro.",
        "..oomsmoo.orrro..",
        "..ogccccgo.ogo...",
        ".odocccco..ogo...",
        ".odoccccoo.ogo...",
        ".odocccco..ogo...",
        "..ookkkkoo.ogo...",
        "..ok...ko..ogo...",
        "..ok...ko..ogo...",
        "..oo...oo..ogo...",
      ],
      [
        ".....gg....ooo...",
        "....oggo..orrro..",
        "....ogo..orrrrro.",
        "...ossso.orrgrro.",
        "...oskso.orrrrro.",
        "..oomsmoo.orrro..",
        "..ogccccgo.ogo...",
        ".odocccco..ogo...",
        ".odoccccoo.ogo...",
        ".odocccco..ogo...",
        "..ookkkkoo.ogo...",
        "...ok.ko...ogo...",
        "...ok.ko...ogo...",
        "...oo.oo...ogo...",
      ],
    ],
    fight: [
      [
        ".....gg..s.ooo...",
        "....oggo.s.rrro..",
        "....ogo..sorrrro.",
        "...ossso.gorrgro.",
        "...oskso.orrrrro.",
        "..oomsmoo.orrro..",
        "..ogccccgo.ogo...",
        ".odocccco..ogo...",
        ".odoccccoo.ogo...",
        ".odocccco..ogo...",
        "..ookkkkoo.ogo...",
        "..ok...ko..ogo...",
        "..ok...ko..ogo...",
        "..oo...oo..ogo...",
      ],
      [
        ".....gg....ooo...",
        "....oggo..orrro..",
        "....ogo..orrrrro.",
        "...ossso.orrgrro.",
        "...osksossorrrro.",
        "..oomsmogo.orro..",
        "..ogccccgo.ogo...",
        ".odocccco..ogo...",
        ".odoccccoo.ogo...",
        ".odocccco..ogo...",
        "..ookkkkoo.ogo...",
        "..ok...ko..ogo...",
        "..ok...ko..ogo...",
        "..oo...oo..ogo...",
      ],
    ],
  },
  knight: {
    frames: [
      [
        "...pp...",
        "..oaao..",
        ".oassao.",
        ".oaaaao.",
        "hhoaaao.",
        "hhoaaao.",
        "hhoaaao.",
        ".oaaao..",
        "..od.do.",
        "..od.do.",
        "..oo.oo.",
      ],
      [
        "...pp...",
        "..oaao..",
        ".oassao.",
        ".oaaaao.",
        "hhoaaao.",
        "hhoaaao.",
        "hhoaaao.",
        ".oaaao..",
        ".od..do.",
        ".od..do.",
        ".oo..oo.",
      ],
    ],
  },
};

export const KNIGHT_PALS = {
  base: { o: INK, a: "#8a8f9a", d: "#5f636d", s: "#e0b088", p: "#b04a3c", h: "#a04a3f" },
  paladin: { o: INK, a: "#d8cfae", d: "#b0a67f", s: "#e0b088", p: "#e0c070", h: "#d8b34a" },
  berserk: { o: INK, a: "#8a5f3f", d: "#63432b", s: "#e0b088", p: "#b04a3c" },
  champion: { o: INK, a: "#e8e0c4", d: "#c8b878", s: "#e0b088", p: "#e8c14a", h: "#d8b34a" },
};

// little characters that stand on towers (and serve as menu icons)
export const MINI = {
  archer: {
    frames: [[
      "...oo.....",
      "..ohho....",
      ".ohhhho...",
      "..osso....",
      ".obbbo.w..",
      "obbbbbow..",
      "obbbbbow..",
      ".obbbo.w..",
      ".obbbo....",
      ".od.do....",
      ".od.do....",
      ".oo.oo....",
    ]],
  },
  // the spire mage grows with his tower: Lv1 apprentice (bare hands, stubble),
  // Lv2 journeyman (staff, proper beard), Lv3+ archmage (hat charm, long
  // beard flowing down the robe). w = beard, t = staff.
  wizardLv1: {
    frames: [[
      "....o.......",
      "....oho.....",
      "...ohhho....",
      "..ohhhhho...",
      ".ohhhhhhho..",
      "...osso.....",
      "...owwo.....",
      ".obbbbbo....",
      ".obbbbbo....",
      ".obbbbbo....",
      ".obbbbbo....",
      ".obbbbbo....",
      "..obbbo.....",
      "..od.do.....",
    ]],
  },
  wizardLv2: {
    frames: [[
      "....o.......",
      "....oho.....",
      "...ohhho....",
      "..ohhhhho...",
      ".ohhhhhhho..",
      "...osso..t..",
      "..owwwwo.t..",
      ".obwwwbo.t..",
      ".obbwbbo.t..",
      ".obbbbbost..",
      ".obbbbbo.t..",
      ".obbbbbo.t..",
      "..obbbo..t..",
      "..od.do..t..",
    ]],
  },
  wizardLv3: {
    frames: [[
      "....o.......",
      "....oho.....",
      "...ohhho....",
      "..ohhghho...",
      ".ohhhhhhho..",
      "...osso..t..",
      "..owwwwo.t..",
      ".obwwwbo.t..",
      ".obwwwbo.t..",
      ".obwwwbost..",
      ".obbwwbo.t..",
      ".obbwbbo.t..",
      "..obbbo..t..",
      "..od.do..t..",
    ]],
  },
  priest: {
    frames: [
      [
        "...omo....",
        "..ommmo...",
        "..osso....",
        "..orro....",
        ".orrrro...",
        ".orrrro...",
        ".orcrro...",
        ".orrrro...",
        ".orrrro...",
        "..orro....",
        "..o..o....",
        "..oo.oo...",
      ],
      [
        "o..omo..o.",
        "o.ommmo.o.",
        "oo.osso.oo",
        ".oorrroo..",
        "..orrrro..",
        ".orrrro...",
        ".orcrro...",
        ".orrrro...",
        ".orrrro...",
        "..orro....",
        "..o..o....",
        "..oo.oo...",
      ],
    ],
  },
};

// menu icons show the full archmage
MINI.wizard = MINI.wizardLv3;

MINI.catapult = {
  frames: [[
    "...oo.........",
    "..oddo........",
    "..odrro.......",
    "...od.o.......",
    "....od........",
    ".....od.......",
    "..oooowdoooo..",
    ".owwwwwwwwwwo.",
    "..ow.o..o.wo..",
    ".oddoo..ooddo.",
    "..oo......oo..",
  ]],
};

export const CATAPULT_PALS = {
  base: { o: INK, w: "#8a6238", d: "#5f4326", r: "#8a8a92" },
  a: { o: INK, w: "#6e4c28", d: "#4a3018", r: "#7d7768" },
  b: { o: INK, w: "#8a6238", d: "#5f4326", r: "#b8b8c0" },
};

export const ARCHER_PALS = {
  base: { o: INK, h: "#54703f", b: "#6e4c28", s: "#e0b088", w: "#4a3018" },
  a: { o: INK, h: "#3f6a34", b: "#4a7a3c", s: "#e0b088", w: "#4a3018" },
  b: { o: INK, h: "#2c3e54", b: "#3a5474", s: "#e0b088", w: "#4a3018" },
  // rank-4 finals: briar (venom green), hawkeye (pale sky), dragonslayer (crimson)
  aa: { o: INK, h: "#2f5230", b: "#3c6a34", s: "#c8d8a0", w: "#4a3018" },
  ab: { o: INK, h: "#9fc4dc", b: "#5a7a94", s: "#e0b088", w: "#4a3018" },
  bb: { o: INK, h: "#8e2f2a", b: "#a0473a", s: "#e0b088", w: "#d8b34a" },
};

// the mounted siege bow of the Ballista ascension
MINI.ballista = {
  frames: [[
    ".o.........o.",
    "obo.......obo",
    "obbo.....obbo",
    ".obbo...obbo.",
    "..obboooobb..",
    "...oomwoo....",
    "..owwwmwwwo..",
    "....odmdo....",
    "....od.do....",
    "...oddoddo...",
    "....o...o....",
  ]],
};
export const BALLISTA_PAL = { o: INK, b: "#6e4c28", w: "#8a6238", d: "#5f4326", m: "#c4c8d0" };

export const WIZ_PALS = {
  base: { o: INK, h: "#5f4a86", b: "#6a5a94", s: "#e0b088", t: "#5f4326", g: "#b08ad8", w: "#e2ded2" },
  a: { o: INK, h: "#a0473a", b: "#8a4034", s: "#e0b088", t: "#5f4326", g: "#d8763a", w: "#e2ded2" },
  b: { o: INK, h: "#7a7434", b: "#98883c", s: "#e0b088", t: "#5f4326", g: "#f0e068", w: "#e2ded2" },
  // rank-4 finals: lava, wildfire, tempest, thunder
  aa: { o: INK, h: "#7d2f1a", b: "#a0473a", s: "#e0b088", t: "#5f4326", g: "#e8c14a", w: "#d8ccc0" },
  ab: { o: INK, h: "#c05a28", b: "#a0473a", s: "#e0b088", t: "#5f4326", g: "#e88a3a", w: "#d8ccc0" },
  ba: { o: INK, h: "#8a883c", b: "#a8a04c", s: "#e0b088", t: "#5f4326", g: "#f8f0a0", w: "#ecead8" },
  bb: { o: INK, h: "#4a4458", b: "#5c5470", s: "#e0b088", t: "#5f4326", g: "#f0f0e0", w: "#e8e8ea" },
};

// Warden Mage: frost-touched at base; deep ice (a) and warm life (b) branches
export const PRIEST_PALS = {
  base: { o: INK, m: "#d8ecf0", r: "#8fb4c4", s: "#e0b088", c: "#7cd4d4" },
  a: { o: INK, m: "#c8ecec", r: "#4a8aa0", s: "#dcecf4", c: "#7cd4d4" },
  b: { o: INK, m: "#bee8b0", r: "#5cae5c", s: "#e0b088", c: "#e8e4d8" },
  // rank-4 finals
  aa: { o: INK, m: "#e8f8fc", r: "#3a7a94", s: "#dcecf4", c: "#b8f0f8" },
  ab: { o: INK, m: "#b8dce8", r: "#2c5a74", s: "#dcecf4", c: "#8cd4e8" },
  ba: { o: INK, m: "#f0ecc8", r: "#b0a04c", s: "#e0b088", c: "#e8d47a" },
  bb: { o: INK, m: "#f4f0e0", r: "#a0473a", s: "#e0b088", c: "#d8b34a" },
};

// Enemies raised by a necromancer wear these instead of their living colors:
// grave-pale flesh, tattered greys, and green witch-fire eyes. Keys mirror
// each type's own palette exactly.
export const UNDEAD_PALS = {
  goblin: { o: INK, g: "#8a9e8e", l: "#a4b8a8", d: "#66786a", e: "#7cc85c", t: "#d8d4c0", b: "#5a5464" },
  wolf: { o: INK, w: "#a0aab8", d: "#707a88", l: "#c0c8d4", e: "#7cc85c", n: "#2b2a33", t: "#d8d4c0" },
  orc: { o: INK, g: "#8a9e8e", l: "#a4b8a8", d: "#66786a", t: "#d8d4c0", e: "#7cc85c", c: "#4a4454", m: "#63666f", b: "#5a5464", s: "#b0a89c" },
};

// the spiked wheel of the Bladewheel, as a build-menu icon
MINI.spiker = {
  frames: [[
    ".....w.....",
    ".w..obo..w.",
    "...obbbo...",
    ".wobbhbbow.",
    "..obhhhbo..",
    ".wobbhbbow.",
    "...obbbo...",
    ".w..obo..w.",
    ".....w.....",
    "....ddd....",
    "...ddddd...",
  ]],
};

export const SPIKER_PALS = {
  base: { o: INK, b: "#9aa0ac", w: "#c4c8d0", h: "#6e4c28", d: "#5f4326" },
  a: { o: INK, b: "#b8bcc4", w: "#dde2ea", h: "#5f636d", d: "#5f4326" },
  b: { o: INK, b: "#8a5a3a", w: "#d8763a", h: "#e8c14a", d: "#5f4326" },
  // rank-4 finals: tempest gold, hamstring frost, solar crown, wildheart embers
  aa: { o: INK, b: "#c4c8d0", w: "#e8d47a", h: "#5f636d", d: "#4a3018" },
  ab: { o: INK, b: "#b8bcc4", w: "#8ce8f0", h: "#5f636d", d: "#4a3018" },
  ba: { o: INK, b: "#a0473a", w: "#e8c14a", h: "#e8d47a", d: "#4a3018" },
  bb: { o: INK, b: "#8a4034", w: "#e88a3a", h: "#d8763a", d: "#4a3018" },
};

// A palette where every key maps to bone-white — used for hit flashes and
// the first beat of death animations. Cached per source palette.
const whiteCache = new WeakMap();
export function whitePal(pal) {
  let w = whiteCache.get(pal);
  if (!w) {
    w = {};
    for (const k of Object.keys(pal)) w[k] = "#f4f2ea";
    whiteCache.set(pal, w);
  }
  return w;
}

// A sprite's `px` is how many world pixels one cell of its map covers. The
// original art is drawn on a coarse grid and keeps px = CELL (2). Hi-res art
// sets `px: 1` and doubles its grid in both directions instead — same size on
// the board, four times the pixels to draw with.
export function drawSprite(ctx, spr, pal, frame, x, y, flip) {
  const map = spr.frames[frame % spr.frames.length];
  const px = spr.px || CELL;
  const h = map.length, w = map[0].length;
  const ox = Math.round((x - (w * px) / 2) / px) * px;
  const oy = Math.round((y - (h * px) / 2) / px) * px;
  let last = null;
  for (let r = 0; r < h; r++) {
    const row = map[r];
    for (let c = 0; c < w; c++) {
      const ch = row[flip ? w - 1 - c : c];
      if (ch === "." || ch === undefined) continue;
      const col = pal[ch];
      if (!col) continue;
      if (col !== last) { ctx.fillStyle = col; last = col; }
      ctx.fillRect(ox + c * px, oy + r * px, px, px);
    }
  }
}
