// ============ PIXEL SPRITES ============
// Hand-made 2-frame sprite maps for every character, their color palettes,
// the little "mini" figures that stand on towers, and the drawSprite routine
// that paints a sprite map onto a canvas one pixel-cell at a time.

import { INK, CELL } from "../data/constants.js";
import { BEAST_SPRITES } from "./beasts.js";
import { UNDEAD_SPRITES } from "./undead.js";
import { IRONHOST_SPRITES } from "./ironhost.js";
import { WILDHOST_SPRITES } from "./wildhost.js";

export const SPRITES = {
  // Hi-res dire wolf (40x24 @ px 1): long and low, streaming tail.
  wolf: {
    pal: { o: INK, w: "#8f929c", d: "#63666f", l: "#aab0ba", e: "#d8b34a", n: "#2b2a33", t: "#ece0c4" },
    px: 1,
    rate: 12,
    frames: [
      [
        "........................................",
        "........................................",
        "............................ooo.ooo.....",
        "............................owo.owo.....",
        "............................owooowo.....",
        ".................oooooooooooodoodoo.....",
        "............ooooooloolllllllowwwwwoo.ooo",
        "..........ooolllllwllwwwwwwwlwwwewwooono",
        "..ooooo..oowwwwwwwwwwwwwwwllwwwwwwwwwwno",
        "..olwwoooowwwwwwwwwwwwwwwlllwwwwwwwwwddo",
        "..ooddwwwwwwwwwwwwwwwwwwlllllwwwwwootooo",
        "...oooddddwwwwwwwwwwwwwwwllllloooooooo..",
        ".....oooooowwwwwwwwwwwwwwwllloo.........",
        "..........ooowddwdddddddowoowo..........",
        "............owoowowoooooowoowoo.........",
        "............oowwoooo...owoooowo.........",
        ".............owwo.....oowo..owoo........",
        ".............oddo.....odoo..oodo........",
        ".............oddo.....odo....odo........",
        ".............oooo.....ooo....ooo........",
        "........................................",
        "........................................",
      ],
      [
        "........................................",
        "........................................",
        "........................................",
        "............................ooo.ooo.....",
        "............................owo.owo.....",
        "............................owooowo.....",
        ".................oooooooooooodoodoo.....",
        "............ooooooloolllllllowwwwwoo.ooo",
        "..........ooolllllwllwwwwwwwlwwwewwooono",
        "..ooo...ooowwwwwwwwwwwwwwwllwwwwwwwwwwno",
        "..olooooowwwwwwwwwwwwwwwwlllwwwwwwwwwddo",
        "..oowwwwwwwwwwwwwwwwwwwwlllllwwwwwootooo",
        "...odddddowwwwwwwwwwwwwwwllllloooooooo..",
        "...oooooooowwwwwwwwwwwwwwwllloo.........",
        "..........ooowddwdddddddowoowo..........",
        "............owoowowoooooowoowo..........",
        "............owoowooo....owoowo..........",
        "............owoowo......owoowo..........",
        "............odoodo......odoodo..........",
        "............odoodo......odoodo..........",
        "............oooooo......oooooo..........",
        "........................................",
      ],
      [
        "........................................",
        "........................................",
        "............................ooo.ooo.....",
        "............................owo.owo.....",
        "............................owooowo.....",
        ".................oooooooooooodoodoo.....",
        "............ooooooloolllllllowwwwwoo.ooo",
        "..........ooolllllwllwwwwwwwlwwwewwooono",
        "..ooo.ooooowwwwwwwwwwwwwwwllwwwwwwwwwwno",
        "..olooowwwwwwwwwwwwwwwwwwlllwwwwwwwwwddo",
        "..oowwwddwwwwwwwwwwwwwwwlllllwwwwwootooo",
        "...odddooowwwwwwwwwwwwwwwllllloooooooo..",
        "...ooooo.oowwwwwwwwwwwwwwwllloo.........",
        "..........ooowddwdddddddowoowo..........",
        "...........oowoowowoooooowoowo..........",
        "...........owoooowoo....oowwoo..........",
        "..........oowo..owoo.....owwo...........",
        "..........odoo..oodo.....oddo...........",
        "..........odo....odo.....oddo...........",
        "..........ooo....ooo.....oooo...........",
        "........................................",
        "........................................",
      ],
      [
        "........................................",
        "........................................",
        "........................................",
        "............................ooo.ooo.....",
        "............................owo.owo.....",
        "............................owooowo.....",
        ".................oooooooooooodoodoo.....",
        "............ooooooloolllllllowwwwwoo.ooo",
        ".....oooooooolllllwllwwwwwwwlwwwewwooono",
        "..oooowwwwowwwwwwwwwwwwwwwllwwwwwwwwwwno",
        "..olwwddddwwwwwwwwwwwwwwwlllwwwwwwwwwddo",
        "..ooddooowwwwwwwwwwwwwwwlllllwwwwwootooo",
        "...oooo.oowwwwwwwwwwwwwwwllllloooooooo..",
        ".........oowwwwwwwwwwwwwwwllloo.........",
        "..........ooowddwdddddddowoowo..........",
        "............owoowowoooooowoowo..........",
        "............owoowooo....owoowo..........",
        "............owoowo......owoowo..........",
        "............odoodo......odoodo..........",
        "............odoodo......odoodo..........",
        "............oooooo......oooooo..........",
        "........................................",
      ],
    ],
    fight: [
      [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "...........................oooooo.......",
        "....................ooo....owoowo.......",
        "...oooo....oooooooooodoooooowoowoo......",
        "...owwooo..odoodowdowwwwwwwowwwewoooooo.",
        "...oddwwoooowwwwwwwwwwwwwwwwwwwwwwwwwno.",
        "...oooddwwwwwwwwwwwwwwwwwllwwwwwwtotooo.",
        ".....ooodwwwwwwwwwwwwwwwlllwwwwwwwoooo..",
        ".......owwwwwwwwwwwwwwwlllllwwwwddtddo..",
        ".......oowwwwwwwwwwwwwwwlllllooooooooo..",
        "........oowwwwwwwwwwwwwwwllloo..........",
        ".........ooowddwdddddddowoowo...........",
        "..........oowoowowoooooowoowoo..........",
        "..........owooowooo...oowooowo..........",
        ".........oowo.oowo....owoo.owoo.........",
        ".........odoo..odo....odo..oodo.........",
        ".........odo...odo....odo...odo.........",
        ".........ooo...ooo....ooo...ooo.........",
      ],
      [
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "............................oooooo......",
        "............................owoowoooo...",
        "..oooo.........ooooooooooooooowwwwewoooo",
        "..owwooo....oooodoodwodwwwwwwwwwwwwwwwww",
        "..oddwwooo..odowwwwwwwwwwwwwwwwwwwwwtoto",
        "..oooddwwoooowwwwwwwwwwwwwwwllwwwwwwwooo",
        "....oooddwwowwwwwwwwwwwwwwwllllwwwwddtdd",
        "......oooddwwwwwwwwwwwwwwwlllllllooooooo",
        "........oooowwwwwwwwwwwwwwwllllloo......",
        "...........oowwwwwwwwwwwwwwwllloo.......",
        "............ooodwddwddddddoowoowo.......",
        "..............owooowwooooooowoowoo......",
        ".............oowoowooo.....oowoowoo.....",
        "............oowooowo........owooowo.....",
        "............odoo.odo........odooodoo....",
        "............odo..odo........oodooodo....",
        "............ooo..ooo.........ooo.ooo....",
        "........................................",
      ],
    ],
  },
  // Hi-res orc (26x26 @ px 1): slab shoulders, tusks, leather harness.
  dragon: {
    pal: { o: INK, r: "#b04a3c", d: "#7d3329", R: "#d2664a", y: "#e0c070", Y: "#f0d696", h: "#ece0c4", e: "#e8c14a", f: "#d88a3f", m: "#5a2622", M: "#8c3a30" },
    px: 1,
    rate: 8,
    frames: [
      [
        "....................................................................",
        "....................................................................",
        "..........................ooo...........ooooo.......................",
        "..........................oMooooo...oooooMoMo.......................",
        "..........................ooMMmmooooommMMoooo.......................",
        "...........................ooMMmmmmmmmMMoo....oooo..................",
        "............................ooMMmomomMMoo.....ohhooo................",
        "............................ooMmmomomMMoo....oooohhoooooo...........",
        "...........................oomoomomoMoomoo...ohhooohhooRoooo........",
        "...........................ommmoommMoommmo...ooohhoodddddddooo......",
        ".........................ooommmmomMMommmmooo...ooohhrRRrRRRRRo......",
        "........................oomommmomoMoMommmomoo..ohoRRrrrreerRRooo....",
        "........................ommommmomooomommmommo..oRRrrrrrrrorrrRRoo...",
        ".......................oommommooMoMohoommommoooorRrrrrrrrrrrrRRRoo..",
        ".......................ommmommoMhoooRMomhommhooRrrrrrddrddrrrrrdRo..",
        "......................oommmoomooRoooroomRommRRRRrrrrdddddddddddffo..",
        "......................omommmhoorrrRrrrrrrrmrrRRrrrrrdoodoodddddofo..",
        "......................ooooomRrrrrRRRrrrrrrrrrrrrrrrdoooooooooooooo..",
        ".......................ooooorrrrrrrrrrrrrrrrrrrrrrddo...............",
        ".......................ohoorrrrrrrrrrrrrrrrrrrrrrddoo...............",
        "....ooo................oRorrrrrrrrrrrrrrrrrrrrrrddoo................",
        "...oohoo..............oorRRrrrrrrrrrrrrrrrrrrrrrdoo.................",
        "...ohoRooo...........ooRrRrrrrrrrrrrrrrrrrrrrrrroo..................",
        "..ooRrRRRoo..........oRRrrrrrrrrrrrryrrrrrrrrrrroo..................",
        "..ohrdrdddo..........oRrrrrrrrrYYYYYYYYYYYrrrrrrdo..................",
        "..oodrdddoo.........oorrrrrrryyyyyyyyyyyyyyyrrrroo..................",
        "...ohorooo.........ooRrrrrrryYYYYYYYYYYYYYYYYrrdo...................",
        "...oohoooo.ooo.ooo.ohorrrrrryyyyyyyyyyyyyyyyyrddo...................",
        "....ooddRoooho.ohoooRrrrrrryyYYYYYYYYYYYYYYYYydoo...................",
        ".....odddddoRoooRooRrRrrrrrryyyyyyyyyyyyyyyyydoo....................",
        ".....oooddddddddddddddddddrryYYYYYYYYYYYYYYYYoo.....................",
        ".......ooooddddddddddddddddddyddyyyyyyyyddyyoo......................",
        "..........ooooooooooooooooddddddYYYYYYYYddooo.......................",
        ".........................oooooddooooyoooddo.........................",
        ".............................oddo..ooo.oddo.........................",
        ".............................oddo......oddo.........................",
        "............................ooddooo...ooddooo.......................",
        "............................ohohoho...ohohoho.......................",
        "............................ooooooo...ooooooo.......................",
        "....................................................................",
        "....................................................................",
        "....................................................................",
        "....................................................................",
        "....................................................................",
        "....................................................................",
        "....................................................................",
      ],
      [
        "....................................................................",
        "....................................................................",
        "....................................................................",
        "....................................................................",
        "....................................................................",
        "..............................................oooo..................",
        "..............................................ohhooo................",
        ".......................ooooo.............oooooooohhoooooo...........",
        ".......................oMoMooooo.....oooooMoMohhooohhooRoooo........",
        ".......................ooooMMmmooooooommMMoooooohhoodddddddooo......",
        "..........................oooMmmmmommmmMooo....ooohhrRRrRRRRRo......",
        "............................ooMmmmommmMoo......ohoRRrrrreerRRooo....",
        "............................oooomoooMMooo......oRRrrrrrrrorrrRRoo...",
        "...........................oommooomohommoo.ooooorRrrrrrrrrrrrRRRoo..",
        ".........................ooommmmhoMoRmmmhooohooRrrrrrddrddrrrrrdRo..",
        ".........................omommmoRooorommRomoRRRRrrrrdddddddddddffo..",
        "........................oomohmorrrrrrrrrrRmRrRRrrrrrdoodoodddddofo..",
        ".......................oommoRrrrrrrrrrrrrrrRrrrrrrrdoooooooooooooo..",
        "......................oommmmrrrrrrrrrrrrrrrrrrrrrrddo...............",
        "......................omhmmrrrrrrrrrrrrrrrrrrrrrrddoo...............",
        "....ooo..............oooRorrrrrrrrrrrrrrrrrrrrrrddoo................",
        "...oohoo.............omorrrrrrrrrrrrrrrrrrrrrrrrdoo.................",
        "...ohoRooo...........oorrrrrrrrrrrrrrrrrrrrrrrrroo..................",
        "..ooRrRRRoo..........orrrrrrrrrrrrrryrrrrrrrrrrroo..................",
        "..ohrdrdddo..........oRrrrrrrrrYYYYYYYYYYYrrrrrrdo..................",
        "..oodrdddoo.........oorrrrrrryyyyyyyyyyyyyyyrrrroo..................",
        "...ohorooo.........ooRrrrrrryYYYYYYYYYYYYYYYYrrdo...................",
        "...oohoooo.ooo.ooo.ohorrrrrryyyyyyyyyyyyyyyyyrddo...................",
        "....ooddRoooho.ohoooRrrrrrryyYYYYYYYYYYYYYYYYydoo...................",
        ".....odddddoRoooRooRrRrrrrrryyyyyyyyyyyyyyyyydoo....................",
        ".....oooddddddddddddddddddrryYYYYYYYYYYYYYYYYoo.....................",
        ".......ooooddddddddddddddddddyddyyyyyyyyddyyoo......................",
        "..........ooooooooooooooooddddddYYYYYYYYddooo.......................",
        ".........................oooooddooooyoooddo.........................",
        ".............................oddo..ooo.oddo.........................",
        ".............................oddo......oddo.........................",
        "............................ooddooo...ooddooo.......................",
        "............................ohohoho...ohohoho.......................",
        "............................ooooooo...ooooooo.......................",
        "....................................................................",
        "....................................................................",
        "....................................................................",
        "....................................................................",
        "....................................................................",
        "....................................................................",
        "....................................................................",
      ],
    ],
  },
  // Hi-res goblin shaman (26x26 @ px 1): deep cowl, bone staff, rune-warded robes.
  ram: {
    pal: { o: INK, w: "#8a6238", d: "#5f4326", m: "#8b93a2", s: "#b9c0cc", k: "#5e6675", c: "#3f6ea8", g: "#d8b34a" },
    px: 1,
    rate: 5,
    frames: [
      [
        ".............ooooo..................................",
        ".............okcco..................................",
        ".............okcoo..................................",
        ".............okoo...ooooooooooooo...................",
        ".............oko..ooogggggggggggooo.................",
        ".............okoooocccccccccccccccooo...............",
        ".............okoockcccckcccckcccckccooo.............",
        "............ookcccccccccccccccccccccccooo...........",
        "..........ooockcccckcccckcccckcccckcccccooo.........",
        "........oooccckcccccccccccccccccccccccccccooo.......",
        "......ooockcccckcccckcccckcccckcccckcccckcccooo.....",
        "....ooocccccccccccccccccccccccccccccccccccccccooo...",
        "....ockcccckcccckcccckcccckcccckcccckcccckcccckco...",
        "....owwwwwwwowwwwwwwwwwwwwowwwwwwwwwwwwwowwwwwwwo...",
        "....owwkwwwwdwwkwwwwwwwkwwdwwwwkwwwwwwwkdwwwwwwko...",
        "....odddddddddddddddddddddddddddddddddddddddddddo...",
        "....owwwwwwwdwwwwwwwwwwwwwdwwwwwwwwwwwwwdwkwwwkwoooo",
        "....owwwwwwwdwwwwwwwwwwwwwdwwwwwwwwwwwwwdwkwwwkwommm",
        "....oddkdddddddkdddddddkdddddddkdddddddkwwwwwwwwwsss",
        "....owwwwwwwdwwwwwwwwwwwwwdwwwwwwwwwwwwwdddddddddmmm",
        "....owwwwwwwdwwwwwwwwwwwwwdwwwwwwwwwwwwwdwwwwwwwoooo",
        "....oddkdddddddkdddddddkdddddddkdddddddkdddddddko...",
        "....owwwwwwwdwwwwwwwwwwwwwdwwwwwwwwwwwwwdwwwwwwwo...",
        "....ooooooooooooooooooooooooooooooooooooooooooooo...",
        ".......odsdo....odddo....odsdo....odddo...odsdo.....",
        ".......odkdo....oskso....odkdo....oskso...odkdo.....",
        ".......odsdo....odddo....odsdo....odddo...odsdo.....",
        ".......odddo....odddo....odddo....odddo...odddo.....",
        ".......ooooo....ooooo....ooooo....ooooo...ooooo.....",
        "....................................................",
        "....................................................",
        "....................................................",
        "....................................................",
        "....................................................",
        "....................................................",
        "....................................................",
        "....................................................",
        "....................................................",
      ],
      [
        "....................................................",
        ".............ooooo..................................",
        ".............okcco..................................",
        ".............okcoo..................................",
        ".............okoo...ooooooooooooo...................",
        ".............oko..ooogggggggggggooo.................",
        ".............okoooocccccccccccccccooo...............",
        ".............okoockcccckcccckcccckccooo.............",
        "............ookcccccccccccccccccccccccooo...........",
        "..........ooockcccckcccckcccckcccckcccccooo.........",
        "........oooccckcccccccccccccccccccccccccccooo.......",
        "......ooockcccckcccckcccckcccckcccckcccckcccooo.....",
        "....ooocccccccccccccccccccccccccccccccccccccccooo...",
        "....ockcccckcccckcccckcccckcccckcccckcccckcccckco...",
        "....owwwwwwwowwwwwwwwwwwwwowwwwwwwwwwwwwowwwwwwwo...",
        "....owwkwwwwdwwkwwwwwwwkwwdwwwwkwwwwwwwkdwwwwwwko...",
        "....odddddddddddddddddddddddddddddddddddddddddddo...",
        "....owwwwwwwdwwwwwwwwwwwwwdwwwwwwwwwwwwwdwwwwwwwo...",
        "....owwwwwwwdwwwwwwwwwwwwwdwwwwwwwwwwwwwdwkwwwkwoooo",
        "....oddkdddddddkdddddddkdddddddkdddddddkddkdddkkommm",
        "....owwwwwwwdwwwwwwwwwwwwwdwwwwwwwwwwwwwwwwwwwwwwsss",
        "....owwwwwwwdwwwwwwwwwwwwwdwwwwwwwwwwwwwdddddddddmmm",
        "....oddkdddddddkdddddddkdddddddkdddddddkdddddddkoooo",
        "....owwwwwwwdwwwwwwwwwwwwwdwwwwwwwwwwwwwdwwwwwwwo...",
        "....ooooooooooooooooooooooooooooooooooooooooooooo...",
        ".......odddo....odsdo....odddo....odsdo...odddo.....",
        ".......oskso....odkdo....oskso....odkdo...oskso.....",
        ".......odddo....odsdo....odddo....odsdo...odddo.....",
        ".......odddo....odddo....odddo....odddo...odddo.....",
        ".......ooooo....ooooo....ooooo....ooooo...ooooo.....",
        "....................................................",
        "....................................................",
        "....................................................",
        "....................................................",
        "....................................................",
        "....................................................",
        "....................................................",
        "....................................................",
      ],
    ],
  },
  // Hi-res Lord Marshal (26x26 @ px 1): gilded plate, war plume, banner-lance.
  knight: {
    px: 1,
    frames: [
      [
        "......pp........",
        ".....pppp.......",
        "....oooooo......",
        "...oaaaaaao.....",
        "...oaaaaaao.....",
        "...oassssao.....",
        "...oaaaaaao.....",
        "....oaaaao......",
        "..oooaaaaooo....",
        ".ohhoaaaaoado...",
        ".ohhhoaaaoado...",
        ".ohhhoaaaoado...",
        ".ohhhoaaaoodo...",
        ".ohhoaaaaao.o...",
        "..ooaaaaaao.....",
        "...oadddao......",
        "...oadddao......",
        "...odo..odo.....",
        "...odo..odo.....",
        "...odo..odo.....",
        "..oo....oo......",
        "................",
      ],
      [
        "......pp........",
        ".....pppp.......",
        "....oooooo......",
        "...oaaaaaao.....",
        "...oaaaaaao.....",
        "...oassssao.....",
        "...oaaaaaao.....",
        "....oaaaao......",
        "..oooaaaaooo....",
        ".ohhoaaaaoado...",
        ".ohhhoaaaoado...",
        ".ohhhoaaaoado...",
        ".ohhhoaaaoodo...",
        ".ohhoaaaaao.o...",
        "..ooaaaaaao.....",
        "...oadddao......",
        "...oadddao......",
        "...odo.odo......",
        "..odo...odo.....",
        "..odo...odo.....",
        ".oo.......oo....",
        "................",
      ],
    ],
  },
};

// The newer rosters live in their own files, one per army, and merge in here
// so every consumer keeps a single SPRITES table to look things up in.
Object.assign(SPRITES, BEAST_SPRITES, UNDEAD_SPRITES, IRONHOST_SPRITES, WILDHOST_SPRITES);

export const KNIGHT_PALS = {
  base: { o: INK, a: "#8a8f9a", d: "#5f636d", s: "#e0b088", p: "#b04a3c", h: "#a04a3f" },
  paladin: { o: INK, a: "#d8cfae", d: "#b0a67f", s: "#e0b088", p: "#e0c070", h: "#d8b34a" },
  berserk: { o: INK, a: "#8a5f3f", d: "#63432b", s: "#e0b088", p: "#b04a3c" },
  champion: { o: INK, a: "#e8e0c4", d: "#c8b878", s: "#e0b088", p: "#e8c14a", h: "#d8b34a" },
};

// little characters that stand on towers (and serve as menu icons)
export const MINI = {
  goldworks: {
    pal: { o: "#2b2a33", g: "#d8b34a", l: "#f0d885", s: "#8a8072", f: "#d8763a" },
    frames: [[
      "....oooo....",
      "...osssso...",
      "...osffso...",
      "...osssso...",
      "..oggogggo..",
      "..ogloglgo..",
      "..oggogggo..",
      "..ogloglgo..",
      "...oooooo...",
    ]],
  },
  trapsmith: {
    pal: { o: "#2b2a33", m: "#8a8f9a", n: "#b8bcc4", w: "#6e4c28" },
    frames: [[
      "on..o..o..no",
      "ono.o..o.ono",
      ".omoooooomo.",
      "..ommmmmmo..",
      "...owwwwo...",
      "..owwwwwwo..",
      "...oooooo...",
    ]],
  },
  assassin: {
    pal: { o: "#2b2a33", c: "#3a3448", h: "#544a68", f: "#c8a888", s: "#b8bcc4", v: "#6a9a52" },
    frames: [[
      "....oooo....",
      "...occcco...",
      "..occhhcco..",
      "..ochffho...",
      "..ochffho...",
      "...ohccho...",
      "..os.oo.vo..",
      "...o....o...",
    ]],
  },
  falconry: {
    pal: { o: "#2b2a33", b: "#a08258", f: "#e8e2d4", k: "#e0b855", w: "#6e4c28" },
    frames: [[
      "....obbo....",
      "...obbbbko..",
      "...obfbbo...",
      "...obffbo...",
      "....obbo....",
      "..ooowwooo..",
      "....owwo....",
      "....owwo....",
    ]],
  },
  sunforge: {
    pal: { o: "#2b2a33", g: "#f4e6b4", k: "#e0b855", d: "#443a52" },
    frames: [[
      "....ogo.....",
      "..oogggoo...",
      "..oggkggo...",
      "..ogkkkgo...",
      "..oggkggo...",
      "...ogggo....",
      "..odogodo...",
      "..odooodo...",
    ]],
  },

  archer: {
    px: 1,
    frames: [[
      "......oo............",
      ".....ohho...........",
      "....ohhhho..........",
      "...ohhhhhho.........",
      "...ohhhhhho.........",
      "....ohsssho.........",
      "....osssso..........",
      ".....osso...........",
      "...oobbboo..w.......",
      "..obbbbbbbo.w.......",
      "..obbbbbbbo.w.......",
      ".obbobbbobbow.......",
      ".obbobbbobbow.......",
      ".obooobbbooow.......",
      ".oso.obbbo.sw.......",
      ".oso.obbbo.sw.......",
      ".....obbbo..w.......",
      "....obbobbo.w.......",
      "....odd.ddo.........",
      "....odd.ddo.........",
      "....odd.ddo.........",
      "....odd.ddo.........",
      "...ooo..ooo.........",
      "....................",
    ]],
  },
  // the spire mage grows with his tower: Lv1 apprentice (bare hands, stubble),
  // Lv2 journeyman (staff, proper beard), Lv3+ archmage (hat charm, long
  // beard flowing down the robe). w = beard, t = staff.
  wizardLv1: {
    px: 1,
    frames: [[
      "..........o.............",
      ".........ooo............",
      "........oohho...........",
      ".......oohhhoo..........",
      "......oohhhhhoo.........",
      ".....oohhhhhhhoo........",
      "....oohhhhhhhhoo........",
      "..oohhhhhhhhhhhoo.......",
      ".ohhhhhhhhhhhhhhho......",
      "..ooooooooooooooo.......",
      "......osssso............",
      "......osssso............",
      "......owwoo.............",
      ".....obbbbbo............",
      "....obbwwbbbo...........",
      "...obbbbbbbbbo..........",
      "...obbbbbbbbbo..........",
      "...obbbbbbbbboo.........",
      "...obbbbbbbbos..........",
      "...obbbbbbbbo...........",
      "...obbbbbbbbo...........",
      "....obbbbbbo............",
      "....obbbbbbo............",
      ".....obbbbo.............",
      ".....od..do.............",
      ".....od..do.............",
      ".....oo..oo.............",
      "........................",
    ]],
  },
  wizardLv2: {
    px: 1,
    frames: [[
      "..........o.............",
      ".........ooo............",
      "........oohho...........",
      ".......oohhhoo..........",
      "......oohhhhhoo.........",
      ".....oohhhhhhhoo........",
      "....oohhhhhhhhoo........",
      "..oohhhhhhhhhhhoo.......",
      ".ohhhhhhhhhhhhhhho......",
      "..ooooooooooooooo.......",
      "......osssso............",
      "......osssso....tt......",
      ".....owwwwwo....tt......",
      "....obwwwwwbo...tt......",
      "....obbwwbbbo...tt......",
      "...obbbbbbbbbo..tt......",
      "...obbbbbbbbbo..tt......",
      "...obbbbbbbbboott.......",
      "...obbbbbbbbostt........",
      "...obbbbbbbbo.tt........",
      "...obbbbbbbbo.tt........",
      "....obbbbbbo..tt........",
      "....obbbbbbo..tt........",
      ".....obbbbo...tt........",
      ".....od..do...tt........",
      ".....od..do...tt........",
      ".....oo..oo...tt........",
      "........................",
    ]],
  },
  wizardLv3: {
    px: 1,
    frames: [[
      "..........o.............",
      ".........ooo............",
      "........oohho...........",
      ".......oohhhoo..........",
      "......oohhhhhoo.........",
      ".....oohhghhhhoo........",
      "....oohhhhhhhhoo........",
      "..oohhhhhhhhhhhoo.......",
      ".ohhhhhhhhhhhhhhho......",
      "..ooooooooooooooo.......",
      "......osssso............",
      "......osssso....tt......",
      ".....owwwwwo....tt......",
      "....obwwwwwbo...tt......",
      "....obbwwbbbo...tt......",
      "...obbbwwbbbbo..tt......",
      "...obbbwwbbbbo..tt......",
      "...obbbwbbbbboott.......",
      "...obbbbbbbbostt........",
      "...obbbbbbbbo.tt........",
      "...obbbbbbbbo.tt........",
      "....obbbbbbo..tt........",
      "....obbbbbbo..tt........",
      ".....obbbbo...tt........",
      ".....od..do...tt........",
      ".....od..do...tt........",
      ".....oo..oo...tt........",
      "........................",
    ]],
  },
  priest: {
    px: 1,
    frames: [
      [
        "........omo.........",
        ".......ommmo........",
        "......ommmmmo.......",
        "......ommmmmo.......",
        ".......ossso........",
        ".......ossso........",
        "......oorroo........",
        ".....orrrrrro.......",
        "....orrrrrrrro......",
        "....orrrrrrrro......",
        "....orrrccrrro......",
        "....orrrccrrro......",
        "....orrrrrrrro......",
        "....orrrrrrrro......",
        "....orrrrrrrro......",
        ".....orrrrrro.......",
        ".....orrrrrro.......",
        "......orrrro........",
        "......o....o........",
        "......oo..oo........",
        "....................",
        "....................",
        "....................",
        "....................",
      ],
      [
        "........omo.........",
        ".......ommmo........",
        "......ommmmmo.......",
        "o.....ommmmmo......o",
        "o......ossso......o.",
        "oo.....ossso.....oo.",
        ".oo..oorroo.....oo..",
        ".....orrrrrro.......",
        "....orrrrrrrro......",
        "....orrrrrrrro......",
        "....orrrccrrro......",
        "....orrrccrrro......",
        "....orrrrrrrro......",
        "....orrrrrrrro......",
        "....orrrrrrrro......",
        ".....orrrrrro.......",
        ".....orrrrrro.......",
        "......orrrro........",
        "......o....o........",
        "......oo..oo........",
        "....................",
        "....................",
        "....................",
        "....................",
      ],
    ],
  },
};

// menu icons show the full archmage
MINI.wizard = MINI.wizardLv3;

MINI.catapult = {
  frames: [[
    "...oo.........",
    "..oddo........",
    "..odrro.......",
    "...od.o.......",
    "....od........",
    ".....od.......",
    "..oooowdoooo..",
    ".owwwwwwwwwwo.",
    "..ow.o..o.wo..",
    ".oddoo..ooddo.",
    "..oo......oo..",
  ]],
};

export const CATAPULT_PALS = {
  base: { o: INK, w: "#8a6238", d: "#5f4326", r: "#8a8a92" },
  a: { o: INK, w: "#6e4c28", d: "#4a3018", r: "#7d7768" },
  b: { o: INK, w: "#8a6238", d: "#5f4326", r: "#b8b8c0" },
};

export const ARCHER_PALS = {
  base: { o: INK, h: "#54703f", b: "#6e4c28", s: "#e0b088", w: "#4a3018" },
  a: { o: INK, h: "#3f6a34", b: "#4a7a3c", s: "#e0b088", w: "#4a3018" },
  b: { o: INK, h: "#2c3e54", b: "#3a5474", s: "#e0b088", w: "#4a3018" },
  // rank-4 finals: briar (venom green), hawkeye (pale sky), dragonslayer (crimson)
  aa: { o: INK, h: "#2f5230", b: "#3c6a34", s: "#c8d8a0", w: "#4a3018" },
  ab: { o: INK, h: "#9fc4dc", b: "#5a7a94", s: "#e0b088", w: "#4a3018" },
  bb: { o: INK, h: "#8e2f2a", b: "#a0473a", s: "#e0b088", w: "#d8b34a" },
};

// the mounted siege bow of the Ballista ascension
MINI.ballista = {
  frames: [[
    ".o.........o.",
    "obo.......obo",
    "obbo.....obbo",
    ".obbo...obbo.",
    "..obboooobb..",
    "...oomwoo....",
    "..owwwmwwwo..",
    "....odmdo....",
    "....od.do....",
    "...oddoddo...",
    "....o...o....",
  ]],
};
export const BALLISTA_PAL = { o: INK, b: "#6e4c28", w: "#8a6238", d: "#5f4326", m: "#c4c8d0" };

export const WIZ_PALS = {
  base: { o: INK, h: "#5f4a86", b: "#6a5a94", s: "#e0b088", t: "#5f4326", g: "#b08ad8", w: "#e2ded2" },
  a: { o: INK, h: "#a0473a", b: "#8a4034", s: "#e0b088", t: "#5f4326", g: "#d8763a", w: "#e2ded2" },
  b: { o: INK, h: "#7a7434", b: "#98883c", s: "#e0b088", t: "#5f4326", g: "#f0e068", w: "#e2ded2" },
  // rank-4 finals: lava, wildfire, tempest, thunder
  aa: { o: INK, h: "#7d2f1a", b: "#a0473a", s: "#e0b088", t: "#5f4326", g: "#e8c14a", w: "#d8ccc0" },
  ab: { o: INK, h: "#c05a28", b: "#a0473a", s: "#e0b088", t: "#5f4326", g: "#e88a3a", w: "#d8ccc0" },
  ba: { o: INK, h: "#8a883c", b: "#a8a04c", s: "#e0b088", t: "#5f4326", g: "#f8f0a0", w: "#ecead8" },
  bb: { o: INK, h: "#4a4458", b: "#5c5470", s: "#e0b088", t: "#5f4326", g: "#f0f0e0", w: "#e8e8ea" },
};

// Warden Mage: frost-touched at base; deep ice (a) and warm life (b) branches
export const PRIEST_PALS = {
  base: { o: INK, m: "#d8ecf0", r: "#8fb4c4", s: "#e0b088", c: "#7cd4d4" },
  a: { o: INK, m: "#c8ecec", r: "#4a8aa0", s: "#dcecf4", c: "#7cd4d4" },
  b: { o: INK, m: "#bee8b0", r: "#5cae5c", s: "#e0b088", c: "#e8e4d8" },
  // rank-4 finals
  aa: { o: INK, m: "#e8f8fc", r: "#3a7a94", s: "#dcecf4", c: "#b8f0f8" },
  ab: { o: INK, m: "#b8dce8", r: "#2c5a74", s: "#dcecf4", c: "#8cd4e8" },
  ba: { o: INK, m: "#f0ecc8", r: "#b0a04c", s: "#e0b088", c: "#e8d47a" },
  bb: { o: INK, m: "#f4f0e0", r: "#a0473a", s: "#e0b088", c: "#d8b34a" },
};

// Enemies raised by a necromancer wear these instead of their living colors:
// grave-pale flesh, tattered greys, and green witch-fire eyes. Keys mirror
// each type's own palette exactly.
export const UNDEAD_PALS = {
  goblin: { o: INK, g: "#8a9e8e", l: "#a4b8a8", d: "#66786a", e: "#7cc85c", t: "#d8d4c0", h: "#4a4454", i: "#5a5464", j: "#38343e", b: "#6a6472", r: "#565060", m: "#7a7a82", n: "#9a9aa2", k: "#242028", a: "#66786a" },
  goblinBare: { o: INK, g: "#8a9e8e", l: "#a4b8a8", d: "#66786a", e: "#7cc85c", t: "#d8d4c0", h: "#4a4454", i: "#5a5464", j: "#38343e", b: "#6a6472", r: "#565060", m: "#7a7a82", n: "#9a9aa2", k: "#242028", a: "#66786a" },
  wolf: { o: INK, w: "#a0aab8", d: "#707a88", l: "#c0c8d4", e: "#7cc85c", n: "#2b2a33", t: "#d8d4c0" },
  orc: { o: INK, g: "#8a9e8e", l: "#a4b8a8", d: "#66786a", t: "#d8d4c0", e: "#7cc85c", h: "#565060", j: "#38343e", m: "#63666f", n: "#7a7a82" },
};

// the spiked wheel of the Bladewheel, as a build-menu icon
MINI.spiker = {
  frames: [[
    ".....w.....",
    ".w..obo..w.",
    "...obbbo...",
    ".wobbhbbow.",
    "..obhhhbo..",
    ".wobbhbbow.",
    "...obbbo...",
    ".w..obo..w.",
    ".....w.....",
    "....ddd....",
    "...ddddd...",
  ]],
};

export const SPIKER_PALS = {
  base: { o: INK, b: "#9aa0ac", w: "#c4c8d0", h: "#6e4c28", d: "#5f4326" },
  a: { o: INK, b: "#b8bcc4", w: "#dde2ea", h: "#5f636d", d: "#5f4326" },
  b: { o: INK, b: "#8a5a3a", w: "#d8763a", h: "#e8c14a", d: "#5f4326" },
  // rank-4 finals: tempest gold, hamstring frost, solar crown, wildheart embers
  aa: { o: INK, b: "#c4c8d0", w: "#e8d47a", h: "#5f636d", d: "#4a3018" },
  ab: { o: INK, b: "#b8bcc4", w: "#8ce8f0", h: "#5f636d", d: "#4a3018" },
  ba: { o: INK, b: "#a0473a", w: "#e8c14a", h: "#e8d47a", d: "#4a3018" },
  bb: { o: INK, b: "#8a4034", w: "#e88a3a", h: "#d8763a", d: "#4a3018" },
};

// A palette where every key maps to bone-white — used for hit flashes and
// the first beat of death animations. Cached per source palette.
const whiteCache = new WeakMap();
export function whitePal(pal) {
  let w = whiteCache.get(pal);
  if (!w) {
    w = {};
    for (const k of Object.keys(pal)) w[k] = "#f4f2ea";
    whiteCache.set(pal, w);
  }
  return w;
}

// A sprite's `px` is how many world pixels one cell of its map covers. The
// original art is drawn on a coarse grid and keeps px = CELL (2). Hi-res art
// sets `px: 1` and doubles its grid in both directions instead — same size on
// the board, four times the pixels to draw with.
export function drawSprite(ctx, spr, pal, frame, x, y, flip) {
  const map = spr.frames[frame % spr.frames.length];
  const px = spr.px || CELL;
  const h = map.length, w = map[0].length;
  const ox = Math.round((x - (w * px) / 2) / px) * px;
  const oy = Math.round((y - (h * px) / 2) / px) * px;
  let last = null;
  for (let r = 0; r < h; r++) {
    const row = map[r];
    for (let c = 0; c < w; c++) {
      const ch = row[flip ? w - 1 - c : c];
      if (ch === "." || ch === undefined) continue;
      const col = pal[ch];
      if (!col) continue;
      if (col !== last) { ctx.fillStyle = col; last = col; }
      ctx.fillRect(ox + c * px, oy + r * px, px, px);
    }
  }
}
