// ============ SPRITES: THE HOLLOW COURT ============
// Hi-res (px 1) hand-made sprite maps for the undead faction. Same grammar as
// sprites.js: a palette of single letters, '.' for nothing, 'o' for the ink
// outline, any number of walk frames plus an optional fight cycle.
//
// The court's look: bone in cold ivory, grave-cloth in drowned violet, and
// every pair of eyes the same witch-fire green -- one color family for the
// whole army, so a mixed wave still reads as ONE court on the march.

import { INK } from "../data/constants.js";

// shared inks
const BONE = "#d8d2c0";      // old ivory
const BONE_DK = "#a89f8c";   // its shadow
const GAP = "#4a463e";       // the dark between ribs
const EYE = "#7ce0b8";       // witch-fire
const CLOTH = "#4c4066";     // drowned violet
const CLOTH_LT = "#5f527e";
const CLOTH_DK = "#37304a";
const RUST = "#8a6248";      // dead men's iron
const FLESH = "#96a48e";     // ghoul-grey
const FLESH_DK = "#76846e";
const FLESH_LT = "#b0bca4";

export const UNDEAD_SPRITES = {
  // ---- RISEN (24x26): the chaff of the court. A dead soldier at a dead
  // man's pace -- sword dragging, jaw loose, one shoulder lower than the other.
  skeleton: {
    pal: { o: INK, b: BONE, d: BONE_DK, k: GAP, e: EYE, r: RUST, c: CLOTH_DK },
    px: 1,
    rate: 7,
    frames: [
      [
        "........oooooo..........",
        ".......obbbbbbo.........",
        "......obbbbbbbbo........",
        "......obbbbbbbbo........",
        "......okeobbokeo........",
        "......obbbbbbbbo........",
        "......odkdkdkbdo........",
        ".......oddddddo.........",
        "........oobbo...........",
        ".....ooobbbbbooo........",
        "....obdbbbbbbbbdbo......",
        "....oboobkbkbboobo......",
        "....odo.obbbbo.odo......",
        "....odo.obkbko.obo......",
        "....odo.obbbbo.odbo.....",
        "....obo.okbbko.odbo.....",
        "....oddo.obbo.oorro.....",
        ".....odo.obbo..orro.....",
        "..........oddoo.orro....",
        ".......oddbbddo.orro....",
        ".......obbo.obo..oo.....",
        ".......obo...obo........",
        ".......obo...obo........",
        "......odbo...odbo.......",
        "......obbo...obbo.......",
        ".....oddo.....oddo......",
        ".....ooo.......ooo......",
      ],
      [
        "........oooooo..........",
        ".......obbbbbbo.........",
        "......obbbbbbbbo........",
        "......obbbbbbbbo........",
        "......okeobbokeo........",
        "......obbbbbbbbo........",
        "......odkdkdkbdo........",
        ".......oddddddo.........",
        "........oobbo...........",
        ".....ooobbbbbooo........",
        "....obdbbbbbbbbdbo......",
        "....oboobkbkbboobo......",
        "....odo.obbbbo.odo......",
        "....odo.obkbko.obo......",
        "....odo.obbbbo.odbo.....",
        "....obo.okbbko.odbo.....",
        "....oddo.obbo.oorro.....",
        ".....odo.obbo..orro.....",
        "..........oddoo.orro....",
        ".......oddbbddo.orro....",
        "........obbobo...oo.....",
        "........obobbo..........",
        "........obobbo..........",
        ".......odbo.obo.........",
        ".......obbo.obbo........",
        "......oddo...oddo.......",
        "......ooo.....ooo.......",
      ],
      [
        "........oooooo..........",
        ".......obbbbbbo.........",
        "......obbbbbbbbo........",
        "......obbbbbbbbo........",
        "......okeobbokeo........",
        "......obbbbbbbbo........",
        "......odkdkdkbdo........",
        ".......oddddddo.........",
        "........oobbo...........",
        ".....ooobbbbbooo........",
        "....obdbbbbbbbbdbo......",
        "....oboobkbkbboobo......",
        "....odo.obbbbo.odo......",
        "....odo.obkbko.obo......",
        "....odo.obbbbo.odbo.....",
        "....obo.okbbko.odbo.....",
        "....oddo.obbo.oorro.....",
        ".....odo.obbo..orro.....",
        "..........oddoo.orro....",
        ".......oddbbddo.orro....",
        ".......obbo.obo..oo.....",
        ".......obo...obo........",
        ".......obo...obo........",
        "......odbo...odbo.......",
        "......obbo...obbo.......",
        ".....oddo.....oddo......",
        ".....ooo.......ooo......",
      ],
      [
        "........oooooo..........",
        ".......obbbbbbo.........",
        "......obbbbbbbbo........",
        "......obbbbbbbbo........",
        "......okeobbokeo........",
        "......obbbbbbbbo........",
        "......odkdkdkbdo........",
        ".......oddddddo.........",
        "........oobbo...........",
        ".....ooobbbbbooo........",
        "....obdbbbbbbbbdbo......",
        "....oboobkbkbboobo......",
        "....odo.obbbbo.odo......",
        "....odo.obkbko.obo......",
        "....odo.obbbbo.odbo.....",
        "....obo.okbbko.odbo.....",
        "....oddo.obbo.oorro.....",
        ".....odo.obbo..orro.....",
        "..........oddoo.orro....",
        ".......oddbbddo.orro....",
        "........obobbo...oo.....",
        "........obbobo..........",
        "........obbobo..........",
        ".......odbo.obo.........",
        ".......obbo.obbo........",
        "......oddo...oddo.......",
        "......ooo.....ooo.......",
      ],
    ],
    fight: [
      [
        "........oooooo..........",
        ".......obbbbbbo.........",
        "......obbbbbbbbo........",
        "......obbbbbbbbo........",
        "......okeobbokeo........",
        "......obbbbbbbbo........",
        "......odkdkdkbdo........",
        ".......oddddddo.........",
        "........oobbo...........",
        ".....ooobbbbboooorro....",
        "....obdbbbbbbbbdborro...",
        "....oboobkbkbboobdrro...",
        "....odo.obbbbo.obdoo....",
        "....odo.obkbko.odo......",
        "....odo.obbbbo.obo......",
        "....obo.okbbko.oo.......",
        "....oddo.obbo...........",
        ".....odo.obbo...........",
        "..........oddoo.........",
        ".......oddbbddo.........",
        ".......obbo.obo.........",
        ".......obo...obo........",
        ".......obo...obo........",
        "......odbo...odbo.......",
        "......obbo...obbo.......",
        ".....oddo.....oddo......",
        ".....ooo.......ooo......",
      ],
      [
        "........oooooo..........",
        ".......obbbbbbo.........",
        "......obbbbbbbbo........",
        "......obbbbbbbbo........",
        "......okeobbokeo........",
        "......obbbbbbbbo........",
        "......odkdkdkbdo........",
        ".......oddddddo.........",
        "........oobbo...........",
        ".....ooobbbbbooo........",
        "....obdbbbbbbbbdboooo...",
        "....oboobkbkbboobrrrro..",
        "....odo.obbbbo.odooooo..",
        "....odo.obkbko.obo......",
        "....odo.obbbbo.odo......",
        "....obo.okbbko.obo......",
        "....oddo.obbo..oo.......",
        ".....odo.obbo...........",
        "..........oddoo.........",
        ".......oddbbddo.........",
        "........obbobo..........",
        "........obobbo..........",
        "........obobbo..........",
        ".......odbo.obo.........",
        ".......obbo.obbo........",
        "......oddo...oddo.......",
        "......ooo.....ooo.......",
      ],
    ],
  },

  // ---- GHOUL (28x20): low, long, and wrong -- it runs on knuckles and feet
  // like something that used to know how to walk upright and gave it up.
  ghoul: {
    pal: { o: INK, f: FLESH, d: FLESH_DK, l: FLESH_LT, e: EYE, t: BONE, k: GAP },
    px: 1,
    rate: 10,
    frames: [
      [
        "............................",
        "...................ooo......",
        "..................offfo.....",
        ".........ooooooooffffffo....",
        "........offfffffffffdffo....",
        ".......offfffffffffoeofo....",
        "......olffffffffffffffo.....",
        "......olfdddffffffdftto.....",
        "......olfo..odffffdotto.....",
        "......offo...offffo.oo......",
        ".....offfo...odfffo.........",
        ".....offo.....offdo.........",
        "....offfo.....offfdo........",
        "....offo.......offfo........",
        "...odffo........offfo.......",
        "...odfo.........odffo.......",
        "..oddfo..........odfo.......",
        "..odddoo.........oddoo......",
        "...oooo...........oooo......",
        "............................",
      ],
      [
        "............................",
        "...................ooo......",
        "..................offfo.....",
        ".........ooooooooffffffo....",
        "........offfffffffffdffo....",
        ".......offfffffffffoeofo....",
        "......olffffffffffffffo.....",
        "......olfdddffffffdftto.....",
        "......olfo..odffffdotto.....",
        "......offo...offffo.oo......",
        ".....offfo...odfffo.........",
        ".....offfo....offdo.........",
        "....offdfo....offfdo........",
        "...offo.offo...odffo........",
        "...offo..offo...odffo.......",
        "..odfo....odo....odfo.......",
        "..odfo.....oo....odfo.......",
        "..oddoo..........oddoo......",
        "...oooo...........oooo......",
        "............................",
      ],
      [
        "............................",
        "...................ooo......",
        "..................offfo.....",
        ".........ooooooooffffffo....",
        "........offfffffffffdffo....",
        ".......offfffffffffoeofo....",
        "......olffffffffffffffo.....",
        "......olfdddffffffdftto.....",
        "......olfo..odffffdotto.....",
        "......offo...offffo.oo......",
        ".....offfo...odfffo.........",
        ".....offo.....offdo.........",
        "....offfo.....offfdo........",
        "....offo.......offfo........",
        "...odffo........offfo.......",
        "...odfo.........odffo.......",
        "..oddfo..........odfo.......",
        "..odddoo.........oddoo......",
        "...oooo...........oooo......",
        "............................",
      ],
    ],
  },

  // ---- BARROW ARCHER (24x26): the Risen's brother with a yew bow, drawn
  // and loosed without breathing. The bow held forward is the silhouette.
  bonearcher: {
    pal: { o: INK, b: BONE, d: BONE_DK, k: GAP, e: EYE, w: "#6a5436", s: "#c8c4b4", c: CLOTH_DK },
    px: 1,
    rate: 7,
    frames: [
      [
        "........oooooo..........",
        ".......obbbbbbo.........",
        "......obbbbbbbbo........",
        "......occbbbbbbo........",
        "......okeobbokeo........",
        "......obbbbbbbbo........",
        "......odkdkdkbdo........",
        ".......oddddddo.........",
        "........oobbo....owo....",
        ".....ooobbbbbooo.owo....",
        "....obdbbbbbbbbdbowo....",
        "....oboobkbkbbooboswo...",
        "....odo.obbbbo.obsswo...",
        "....odo.obkbko.obbowo...",
        "....odo.obbbbo.odo.wo...",
        "....obo.okbbko.obo.owo..",
        "....oddo.obbo..oo..owo..",
        ".....odo.obbo.......oo..",
        "..........oddoo.........",
        ".......oddbbddo.........",
        ".......obbo.obo.........",
        ".......obo...obo........",
        ".......obo...obo........",
        "......odbo...odbo.......",
        "......obbo...obbo.......",
        ".....oddo.....oddo......",
      ],
      [
        "........oooooo..........",
        ".......obbbbbbo.........",
        "......obbbbbbbbo........",
        "......occbbbbbbo........",
        "......okeobbokeo........",
        "......obbbbbbbbo........",
        "......odkdkdkbdo........",
        ".......oddddddo.........",
        "........oobbo....owo....",
        ".....ooobbbbbooo.owo....",
        "....obdbbbbbbbbdbowo....",
        "....oboobkbkbbooboswo...",
        "....odo.obbbbo.obsswo...",
        "....odo.obkbko.obbowo...",
        "....odo.obbbbo.odo.wo...",
        "....obo.okbbko.obo.owo..",
        "....oddo.obbo..oo..owo..",
        ".....odo.obbo.......oo..",
        "..........oddoo.........",
        ".......oddbbddo.........",
        "........obbobo..........",
        "........obobbo..........",
        "........obobbo..........",
        ".......odbo.obo.........",
        ".......obbo.obbo........",
        "......oddo...oddo.......",
      ],
    ],
  },

  // ---- WRAITH (22x28): no feet, no floor. A hood with a cold light in it
  // and a hem that frays into the air. It reads as a hole in the world.
  wraith: {
    pal: { o: INK, c: CLOTH, l: CLOTH_LT, d: CLOTH_DK, e: EYE, g: "#b8f0dc", k: "#241f30" },
    px: 1,
    rate: 4,
    frames: [
      [
        "........oooooo........",
        ".......occcccco.......",
        "......olcccccclo......",
        ".....olccooooccdo.....",
        ".....occokkkkocdo.....",
        ".....occkekekkcdo.....",
        ".....occokkkkocdo.....",
        ".....occcokkoccdo.....",
        "......occccccddo......",
        ".....occccccccddo.....",
        "....olcccccccccddo....",
        "....olccccccccccdo....",
        "...olccccdccccccddo...",
        "...occcccdcccccccdo...",
        "...occcccddccccccdo...",
        "..occcccccdcccccddo...",
        "..occcccccdccccccdo...",
        "..occcccccddccccddo...",
        "...occcccccdccccdo....",
        "...occcocccdcccddo....",
        "....ocdo.occdoccdo....",
        "....occo..occo.odo....",
        ".....odo..occo.odo....",
        ".....odo...odo..oo....",
        "......oo...odo........",
        "............oo........",
        "......................",
        "......................",
      ],
      [
        "......................",
        "........oooooo........",
        ".......occcccco.......",
        "......olcccccclo......",
        ".....olccooooccdo.....",
        ".....occokkkkocdo.....",
        ".....occkekekkcdo.....",
        ".....occokkkkocdo.....",
        ".....occcokkoccdo.....",
        "......occccccddo......",
        ".....occccccccddo.....",
        "....olcccccccccddo....",
        "....olccccccccccdo....",
        "...olccccdccccccddo...",
        "...occcccdcccccccdo...",
        "...occcccddccccccdo...",
        "..occcccccdcccccddo...",
        "..occcccccdccccccdo...",
        "..occcccccddccccddo...",
        "...occcccccdccccdo....",
        "...occcocccdcccddo....",
        "....ocdo.occdoccdo....",
        "....odo...occo.odo....",
        ".....oo...occo.odo....",
        "...........odo..oo....",
        "...........odo........",
        "............oo........",
        "......................",
      ],
    ],
  },

  // ---- PLAGUE GHAST (24x24): a belly with a body around it. Swollen,
  // stitched, and leaking -- everything about it says "do.not.pop.this.here".
  ghast: {
    pal: { o: INK, f: "#8aa06a", d: "#6a8050", l: "#a8bc84", e: EYE, s: "#4c5a3a", p: "#c8d89a", k: GAP },
    px: 1,
    rate: 5,
    frames: [
      [
        "..........oooo..........",
        ".........offffo.........",
        ".........ofdfdfo........",
        ".........okeokeo........",
        ".........offffdo........",
        "..........odsdo.........",
        ".......ooofffffooo......",
        ".....oofffffffffffoo....",
        "....offlffffffffffffo...",
        "...ofllffffsffffffdfo...",
        "...oflfffffsfffffffdo...",
        "..oflffffffsffffffddo...",
        "..oflfffpffsfffpfffdo...",
        "..olffffffssssfffffdo...",
        "..olffpffffffffffpddo...",
        "..oflffffffpffffffddo...",
        "..offdffffffffffdddo....",
        "...offddffffffdddddo....",
        "...ooffffddddffffoo.....",
        ".....offo....offo.......",
        ".....offo....offo.......",
        "....odffo....odffo......",
        "....oddo......oddo......",
        ".....oo........oo.......",
      ],
      [
        "..........oooo..........",
        ".........offffo.........",
        ".........ofdfdfo........",
        ".........okeokeo........",
        ".........offffdo........",
        "..........odsdo.........",
        ".......ooofffffooo......",
        ".....oofffffffffffoo....",
        "....offlffffffffffffo...",
        "...ofllffffsffffffdfo...",
        "...oflfffffsfffffffdo...",
        "..oflffffffsffffffddo...",
        "..oflfffpffsfffpfffdo...",
        "..olffffffssssfffffdo...",
        "..olffpffffffffffpddo...",
        "..oflffffffpffffffddo...",
        "..offdffffffffffdddo....",
        "...offddffffffdddddo....",
        "...ooffffddddffffoo.....",
        ".....offo.....offo......",
        "....offo......offdo.....",
        "....odfo.......odfo.....",
        "....oddo.......oddo.....",
        ".....oo.........oo......",
      ],
    ],
  },

  // ---- CRYPT WARDEN (26x28): the sarcophagus lid fills the front — a
  // carved sleeping king, eyes shut, hands crossed in relief. Over the top:
  // the warden's horned iron helm and one living point of witch-fire.
  crypt: {
    pal: { o: INK, s: "#9a9484", t: "#b4ad9a", d: "#767060", m: "#555044", e: EYE, a: "#5a5a64", h: "#43434c", k: GAP },
    px: 1,
    rate: 4,
    frames: [
      [
        "..........................",
        "...oo..............oo.....",
        "..oaao....oooo....oaao....",
        "..oahaoooaaaaaaoooaha.o...",
        "...oahaaaaaaaaaaaaha.o....",
        "....oaaaaoaaaaoaaaa.o.....",
        ".....oaaaeaaaaeaaao.......",
        "....ooaaaaaaaaaaaoo.......",
        "...otssssssssssssto.......",
        "...ostttttttttttsdo.......",
        "...osttosstssottsdo.......",
        "...osttssttsstttsdo.......",
        "...ostosmmssmmsotdo.......",
        "...osttsmostmosttdo.......",
        "...osttssssssttssdo.......",
        "...ostttosssso.ttdo.......",
        "...osttssmmmssttsdo.......",
        "...osttmmsttsmmttdo.......",
        "...ostttmmssmmtttdo.......",
        "...osttttmmmmttssdo.......",
        "...ossttttttttttsdo.......",
        "...odsssssssssssddo.......",
        "....oddddddddddddo........",
        ".....ooo.oo.ooo...........",
        "....oaaao..oaaao..........",
        "....oahao..oahao..........",
        "...odaaao.odaaao..........",
        "....oooo...oooo...........",
      ],
      [
        "..........................",
        "...oo..............oo.....",
        "..oaao....oooo....oaao....",
        "..oahaoooaaaaaaoooaha.o...",
        "...oahaaaaaaaaaaaaha.o....",
        "....oaaaaoaaaaoaaaa.o.....",
        ".....oaaaeaaaaeaaao.......",
        "....ooaaaaaaaaaaaoo.......",
        "...otssssssssssssto.......",
        "...ostttttttttttsdo.......",
        "...osttosstssottsdo.......",
        "...osttssttsstttsdo.......",
        "...ostosmmssmmsotdo.......",
        "...osttsmostmosttdo.......",
        "...osttssssssttssdo.......",
        "...ostttosssso.ttdo.......",
        "...osttssmmmssttsdo.......",
        "...osttmmsttsmmttdo.......",
        "...ostttmmssmmtttdo.......",
        "...osttttmmmmttssdo.......",
        "...ossttttttttttsdo.......",
        "...odsssssssssssddo.......",
        "....oddddddddddddo........",
        ".....ooo.oo.ooo...........",
        "....oaaao...oaaao.........",
        "....oahao...oahao.........",
        "....odaao..odaaao.........",
        ".....ooo....oooo..........",
      ],
    ],
  },

  // ---- GRAVECALLER (24x28): a robe, a reach, and a bell. The bell arm
  // swings between frames -- that swing is the whole animation, because the
  // bell is the whole threat.
  gravecaller: {
    pal: { o: INK, c: CLOTH, l: CLOTH_LT, d: CLOTH_DK, e: EYE, g: "#c8b874", k: "#241f30", b: BONE_DK },
    px: 1,
    rate: 4,
    frames: [
      [
        "........oooooo..........",
        ".......occcccco.........",
        "......occcccccco........",
        ".....occooooooccdo......",
        ".....occkkkkkkocdo......",
        ".....occkkekekkcdo......",
        ".....occokkkkkocdo......",
        "......occcccccddo.......",
        ".....olcccccccddo.......",
        "....olccccccccccdo......",
        "....olcccdccccccdo......",
        "...olccccdccccccddo.....",
        "...occcccdcccccccdoobo..",
        "...occcccddccccccdobbo..",
        "..occcccccdcccccddoogo..",
        "..occcccccdccccccdoggo..",
        "..occcccccddccccddogggo.",
        "..occccccccdccccdo.oggo.",
        "..occccccccdccccddo.oo..",
        "..occccccccdccccccdo....",
        "..occcccccddddccccdo....",
        "..occcccddccccddccdo....",
        "..occcddcccccccddcdo....",
        "..occdcccccccccccddo....",
        "..ocdcccccccccccccdo....",
        "..odccccccccccccccdo....",
        "..oddddddddddddddddo....",
        "...ooooooooooooooo......",
      ],
      [
        "........oooooo..........",
        ".......occcccco.........",
        "......occcccccco........",
        ".....occooooooccdo......",
        ".....occkkkkkkocdo......",
        ".....occkkekekkcdo......",
        ".....occokkkkkocdo......",
        "......occcccccddo.......",
        ".....olcccccccddo.......",
        "....olccccccccccdo......",
        "....olcccdccccccdo......",
        "...olccccdccccccddo.....",
        "...occcccdcccccccdo.....",
        "...occcccddccccccdoobo..",
        "..occcccccdcccccddobbo..",
        "..occcccccdccccccdoogo..",
        "..occcccccddccccddoggo..",
        "..occccccccdccccdogggo..",
        "..occccccccdccccddoggo..",
        "..occccccccdccccccdoo...",
        "..occcccccddddccccdo....",
        "..occcccddccccddccdo....",
        "..occcddcccccccddcdo....",
        "..occdcccccccccccddo....",
        "..ocdcccccccccccccdo....",
        "..odccccccccccccccdo....",
        "..oddddddddddddddddo....",
        "...ooooooooooooooo......",
      ],
    ],
  },

  // ---- GRAVE AMALGAM (32x26): several dead things that gave up on being
  // several. Heads where heads shouldn't be, arms that agree on nothing,
  // one slow tide of a stride.
  amalgam: {
    pal: { o: INK, f: FLESH, d: FLESH_DK, l: FLESH_LT, e: EYE, b: BONE, k: GAP, s: "#4c5a3a" },
    px: 1,
    rate: 4,
    frames: [
      [
        "..........oooo....ooo...........",
        ".........offffo..obbbo..........",
        ".........ofdfdo..obeobo.........",
        ".........okeoko..obbbbo.........",
        ".....oooooffffoooobbdo..........",
        "....offffffffffffffddoo.........",
        "...offlfffffffffffffffoo........",
        "..offllffffsffffffffffdfo.......",
        "..oflffffffsfffffffffffdo.......",
        ".oflfffffffsffffbfffffddo.......",
        ".oflffofffssfffobofffffdo.......",
        ".olffobofffffffobbofffddoooo....",
        ".olffobbofffffffbofffffdoffdo...",
        ".offfobofffffffffffffffffffdo...",
        ".offdffffffkeoffffffffdddffdo...",
        "..offdffffokkoffffffdddddffo....",
        "..offfdddffooffffdddddddddo.....",
        "...offffddddddddddddddoooo......",
        "...oofffffffdddddffffoo.........",
        ".....offfo......offfo...........",
        ".....offfo......offfo...........",
        "....odfffo.....odfffo...........",
        "....odffo......odffo............",
        "...oddffo.....oddffo............",
        "....oddo.......oddo.............",
        ".....oo.........oo..............",
      ],
      [
        "..........oooo....ooo...........",
        ".........offffo..obbbo..........",
        ".........ofdfdo..obeobo.........",
        ".........okeoko..obbbbo.........",
        ".....oooooffffoooobbdo..........",
        "....offffffffffffffddoo.........",
        "...offlfffffffffffffffoo........",
        "..offllffffsffffffffffdfo.......",
        "..oflffffffsfffffffffffdo.......",
        ".oflfffffffsffffbfffffddo.......",
        ".oflffofffssfffobofffffdo.......",
        ".olffobofffffffobbofffddoooo....",
        ".olffobbofffffffbofffffdoffdo...",
        ".offfobofffffffffffffffffffdo...",
        ".offdffffffkeoffffffffdddffdo...",
        "..offdffffokkoffffffdddddffo....",
        "..offfdddffooffffdddddddddo.....",
        "...offffddddddddddddddoooo......",
        "...oofffffffdddddffffoo.........",
        ".....offfo.......offfo..........",
        "....offfo........offfdo.........",
        "....odffo.......odfffo..........",
        "...odffo.........odffo..........",
        "...oddfo.........oddfo..........",
        "....oddo..........oddo..........",
        ".....oo............oo...........",
      ],
    ],
  },

  // ---- THE HOLLOW KING (30x32): the crown is the silhouette -- five dead
  // points of tarnished gold over a face that is mostly light. Robe to the
  // floor; nothing so common as legs.
  hollowking: {
    pal: { o: INK, c: "#3f3658", l: "#544878", d: "#2c2540", e: EYE, g: "#b09a54", k: "#1c1828", b: BONE, s: "#8adcc0" },
    px: 1,
    rate: 3,
    frames: [
      [
        "....og..og.ogo.go..go.........",
        "....ogo.ogoogoogo.ogo.........",
        "....oggoogggggggooggo.........",
        ".....ogggggggggggggo..........",
        ".....oggggggggggggo...........",
        "......oooooooooooo............",
        "......okkkkkkkkkko............",
        "......okkekkkekkko............",
        "......okkkkkkkkkko............",
        "......okkkssskkkko............",
        ".......okkkkkkkko.............",
        "......ooccccccccoo............",
        ".....olcccccccccddo...........",
        "....olcccccccccccddo..........",
        "...olcccccdcccccccddo.........",
        "...occccccdcccccccddo.........",
        "..olccccccdccccccccdo.obo.....",
        "..olcccccddcccccccddo.obbo....",
        "..occcccccdcccccccddoogbgo....",
        "..occcccccdccccccccdogggo.....",
        "..occcccccddccccccddosggo.....",
        "..occccccccdcccccccdosso......",
        "..occccccccdccccccddoso.......",
        "..occcccccddddcccccdoo........",
        "..occccccddccddcccccdo........",
        "..occccddcccccddccccdo........",
        "..occcdccccccccddcccdo........",
        "..occdccccccccccdddcdo........",
        "..ocdcccccccccccccdddo........",
        "..odccccccccccccccccdo........",
        "..oddddddddddddddddddo........",
        "...oooooooooooooooooo.........",
      ],
      [
        "....og..og.ogo.go..go.........",
        "....ogo.ogoogoogo.ogo.........",
        "....oggoogggggggooggo.........",
        ".....ogggggggggggggo..........",
        ".....oggggggggggggo...........",
        "......oooooooooooo............",
        "......okkkkkkkkkko............",
        "......okkekkkekkko............",
        "......okkkkkkkkkko............",
        "......okkkssskkkko............",
        ".......okkkkkkkko.............",
        "......ooccccccccoo............",
        ".....olcccccccccddo...........",
        "....olcccccccccccddo..........",
        "...olcccccdcccccccddo.........",
        "...occccccdcccccccddo.........",
        "..olccccccdccccccccdoobo......",
        "..olcccccddcccccccddobbo......",
        "..occcccccdcccccccddgbgo......",
        "..occcccccdccccccccdgggoo.....",
        "..occcccccddccccccddsggoo.....",
        "..occccccccdcccccccdssoo......",
        "..occccccccdccccccddso........",
        "..occccccccddddccccdoo........",
        "..occcccccddccddcccccdo.......",
        "..occccddccccccddccccdo.......",
        "..occcdccccccccccddccdo.......",
        "..occdccccccccccccddddo.......",
        "..ocdcccccccccccccccddo.......",
        "..odcccccccccccccccccdo.......",
        "..oddddddddddddddddddo........",
        "...ooooooooooooooooo..........",
      ],
    ],
  },
};
